/*
 * test_web_form -- the generated form is RUN, not just parsed.
 *
 * `web/form.js` turns a field the contract describes into the one
 * control that field's own constraints call for (ADR-0338, #595), and
 * until this existed the only gate over it was `test_web_syntax`, which
 * proves a file parses. That distinction is not academic here: three
 * releases in one day shipped a `web/api.js` that parsed every
 * assertion put to it and would not load in a browser (#594), and the
 * check that caught them was the one that handed the file to a real
 * engine.
 *
 * So this hands the engine the real generated `web/api.js` and the real
 * `web/form.js`, over a DOM small enough to write down, and asserts
 * what an operator would otherwise have to open the dashboard to see:
 *
 *   - a field the contract marks `format: password` renders obscured,
 *     which is the whole reason those eight fields carry it;
 *   - an `enum` renders as a select carrying exactly its own values,
 *     in contract order;
 *   - a numeric field carries the contract's own minimum and maximum,
 *     so a form refuses what the daemon would refuse;
 *   - an empty optional field is OMITTED from the body rather than sent
 *     as "", because every partial-update endpoint here reads an absent
 *     key as "leave it alone";
 *   - a boolean is a checkbox and arrives as a boolean, not as "on".
 *
 * The DOM shim is deliberately the smallest thing form.js actually
 * uses. It is not a browser, and a test that needed more of one would
 * be a sign the renderer had grown a dependency it should not have.
 */
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quickjs.h"

_Static_assert(JS_LIMB_BITS == 32,
               "quickjs.h took the __int128 arm under this compiler, but the library is "
               "built with -U__SIZEOF_INT128__ on the other one -- see "
               "recipes/package/quickjs/2026-06-04-3");

static int g_fail;

static void fail(const char *fmt, ...)
{
	va_list ap;

	fprintf(stderr, "FAIL: ");
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fprintf(stderr, "\n");
	g_fail = 1;
}

static char *read_file(const char *path, size_t *out_len)
{
	FILE *f = fopen(path, "rb");
	long n;
	char *buf;

	if (f == NULL)
		return NULL;
	if (fseek(f, 0, SEEK_END) != 0) {
		fclose(f);
		return NULL;
	}
	n = ftell(f);
	if (n < 0 || fseek(f, 0, SEEK_SET) != 0) {
		fclose(f);
		return NULL;
	}
	buf = malloc((size_t)n + 1);
	if (buf == NULL) {
		fclose(f);
		return NULL;
	}
	if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
		free(buf);
		fclose(f);
		return NULL;
	}
	buf[n] = '\0';
	fclose(f);
	if (out_len != NULL)
		*out_len = (size_t)n;
	return buf;
}

/* Evaluates one file, reporting what the engine said about it. */
static int run_file(JSContext *ctx, const char *path)
{
	size_t len = 0;
	char *src = read_file(path, &len);
	JSValue v;
	int bad;

	if (src == NULL) {
		fail("could not read %s -- api.js is generated by apigen and is a "
		     "prerequisite of the build, so an absent one is a broken build and not "
		     "a reason to skip this",
		     path);
		return -1;
	}
	v = JS_Eval(ctx, src, len, path, JS_EVAL_TYPE_GLOBAL);
	bad = JS_IsException(v);
	if (bad) {
		JSValue e = JS_GetException(ctx);
		const char *msg = JS_ToCString(ctx, e);

		fail("%s threw while loading: %s", path, msg != NULL ? msg : "(no message)");
		if (msg != NULL)
			JS_FreeCString(ctx, msg);
		JS_FreeValue(ctx, e);
	}
	JS_FreeValue(ctx, v);
	free(src);
	return bad ? -1 : 0;
}

/*
 * The DOM, as far as form.js reaches into it: an element with a
 * mutable property bag, children, a dataset, and querySelectorAll over
 * the one attribute the body collector selects on.
 */
static const char *const DOM_SHIM =
    /*
     * The six globals form.js expects app.js to have defined, stubbed
     * to record rather than act. `openModal` empties the form first,
     * exactly as the real one does by calling closeModal() -- which is
     * the whole reason this stub is worth having: the first draft of
     * openForm() built its fields and THEN opened the modal, so every
     * form would have opened empty, and nothing but reading the code
     * caught it.
     */
    "globalThis.opened = null;\n"
    "globalThis.openModal = (id, title) => {\n"
    "  globalThis.opened = { id: id, title: title };\n"
    "  document.getElementById(\"generated-form\").textContent = \"\";\n"
    "};\n"
    "globalThis.sessionMay = () => true;\n"
    "globalThis.sessionRefusal = () => \"no\";\n"
    "globalThis.status_said = null;\n"
    "globalThis.showStatus = (m) => { globalThis.status_said = m; };\n"
    "globalThis.runRefreshers = async () => {};\n"
    "globalThis.refreshersForView = () => [];\n"
    "globalThis.document = {\n"
    "  getElementById(id) {\n"
    "    if (this._byId === undefined)\n"
    "      this._byId = {};\n"
    "    if (this._byId[id] === undefined) {\n"
    "      this._byId[id] = this.createElement(\"form\");\n"
    "      this._byId[id].id = id;\n"
    "    }\n"
    "    return this._byId[id];\n"
    "  },\n"
    "  querySelector() { return null; },\n"
    "  createElement(tag) {\n"
    "    const el = {\n"
    "      tag: tag, dataset: {}, children: [],\n"
    "      appendChild(c) { this.children.push(c); },\n"
    "      querySelectorAll(sel) {\n"
    "        const out = [];\n"
    "        const walk = (n) => {\n"
    "          for (const c of n.children) {\n"
    "            if (sel === \"[data-field]\" && c.dataset.field !== undefined)\n"
    "              out.push(c);\n"
    "            walk(c);\n"
    "          }\n"
    "        };\n"
    "        walk(this);\n"
    "        return out;\n"
    "      },\n"
    "    };\n"
    /*
     * textContent is an ACCESSOR, not a field, because the one DOM
     * behaviour the renderer depends on is that assigning "" removes
     * every child. A plain property would record the assignment and
     * keep the children, which would make this shim agree with a bug
     * instead of catching it.
     */
    "    let text = \"\";\n"
    "    Object.defineProperty(el, \"textContent\", {\n"
    "      get() { return text; },\n"
    "      set(v) { text = v; if (v === \"\") el.children.length = 0; },\n"
    "    });\n"
    "    return el;\n"
    "  },\n"
    "};\n";

/* Runs an expression and returns its value as a freshly allocated
 * string, or NULL having already reported why not. */
static char *eval_str(JSContext *ctx, const char *expr, const char *what)
{
	JSValue v = JS_Eval(ctx, expr, strlen(expr), what, JS_EVAL_TYPE_GLOBAL);
	const char *s;
	char *copy = NULL;

	if (JS_IsException(v)) {
		JSValue e = JS_GetException(ctx);
		const char *msg = JS_ToCString(ctx, e);

		fail("%s threw: %s", what, msg != NULL ? msg : "(no message)");
		if (msg != NULL)
			JS_FreeCString(ctx, msg);
		JS_FreeValue(ctx, e);
		JS_FreeValue(ctx, v);
		return NULL;
	}
	s = JS_ToCString(ctx, v);
	if (s != NULL) {
		copy = strdup(s);
		JS_FreeCString(ctx, s);
	}
	JS_FreeValue(ctx, v);
	return copy;
}

static void expect(JSContext *ctx, const char *what, const char *expr, const char *want)
{
	char *got = eval_str(ctx, expr, what);

	if (got == NULL)
		return;
	if (strcmp(got, want) != 0)
		fail("%s: expected `%s`, got `%s`", what, want, got);
	free(got);
}

int main(void)
{
	JSRuntime *rt = JS_NewRuntime();
	JSContext *ctx;

	if (rt == NULL) {
		fprintf(stderr, "FAIL: could not create a JS runtime\n");
		return 1;
	}
	ctx = JS_NewContext(rt);
	if (ctx == NULL) {
		fprintf(stderr, "FAIL: could not create a JS context\n");
		JS_FreeRuntime(rt);
		return 1;
	}

	if (JS_IsException(JS_Eval(ctx, DOM_SHIM, strlen(DOM_SHIM), "<dom>",
	                           JS_EVAL_TYPE_GLOBAL)))
		fail("the DOM shim itself does not load");
	else if (run_file(ctx, "web/api.js") == 0 && run_file(ctx, "web/form.js") == 0) {
		/*
		 * Each assertion names a REAL field of a REAL schema, so the
		 * contract and the renderer are checked against each other
		 * rather than against a fixture that could drift from both.
		 */
		expect(ctx, "a field name reads as a label", "fieldLabel(\"prefix_len\")",
		       "Prefix len");

		/* postLogin's password: the first reason `format: password`
		 * exists in the contract at all. */
		expect(ctx, "a password field is obscured",
		       "fieldControl(CIX_API.FIELDS.postLoginRequest.find("
		       "(f) => f.name === \"password\")).type",
		       "password");
		expect(ctx, "a plain string field is not",
		       "fieldControl(CIX_API.FIELDS.postLoginRequest.find("
		       "(f) => f.name === \"username\")).type",
		       "text");

		/* NetworkCreateRequest's prefix_len carries minimum: 8 and
		 * maximum: 30, which no hand-written form carried. */
		expect(ctx, "a numeric field carries the contract's minimum",
		       "fieldControl(CIX_API.FIELDS.NetworkCreateRequest.find("
		       "(f) => f.name === \"prefix_len\")).min",
		       "8");
		expect(ctx, "a numeric field carries the contract's maximum",
		       "fieldControl(CIX_API.FIELDS.NetworkCreateRequest.find("
		       "(f) => f.name === \"prefix_len\")).max",
		       "30");

		/* The NTP binding's container carries a pattern, moved into
		 * the contract when its hand-written form was retired. */
		expect(ctx, "a string field carries the contract's pattern",
		       "fieldControl(CIX_API.FIELDS.NtpServerBindingCreateRequest.find("
		       "(f) => f.name === \"container\")).pattern",
		       "^[A-Za-z0-9_-]+$");
		expect(ctx, "a required field is required",
		       "String(fieldControl(CIX_API.FIELDS.NtpServerBindingCreateRequest.find("
		       "(f) => f.name === \"container\")).required)",
		       "true");

		/* An enum becomes a select carrying its own values, in order,
		 * and the one written across two lines in the contract is the
		 * one to check (#602). */
		expect(ctx, "an enum becomes a select",
		       "fieldControl(CIX_API.FIELDS.SourceCatalogueEntry.find("
		       "(f) => f.name === \"stage\")).tag",
		       "select");
		expect(ctx, "a select carries every value the contract lists",
		       "fieldControl(CIX_API.FIELDS.SourceCatalogueEntry.find("
		       "(f) => f.name === \"stage\")).children.map((o) => o.value).join(\",\")",
		       "discover,resolve,authenticate,author,fetch,unpack,build,install,publish,"
		       "roll,deploy,acquire,assemble,stage,verify");

		/*
		 * And the body. An empty optional is omitted, an empty
		 * REQUIRED one is sent (so the daemon's own refusal is what
		 * the operator sees, rather than the form quietly dropping a
		 * key the endpoint demands), a boolean is a boolean, and a
		 * comma-separated list is an array.
		 */
		expect(ctx, "an empty optional field is omitted from the body",
		       "(() => {\n"
		       "  const f = document.createElement(\"form\");\n"
		       "  const a = document.createElement(\"input\");\n"
		       "  const b = document.createElement(\"input\");\n"
		       "  a.dataset.field = \"kept\"; a.dataset.ftype = \"string\"; a.value = \"x\";\n"
		       "  b.dataset.field = \"gone\"; b.dataset.ftype = \"string\"; b.value = \"\";\n"
		       "  f.appendChild(a); f.appendChild(b);\n"
		       "  return JSON.stringify(generatedFormBody(f));\n"
		       "})()",
		       "{\"kept\":\"x\"}");
		expect(ctx, "a checkbox arrives as a boolean and a list as an array",
		       "(() => {\n"
		       "  const f = document.createElement(\"form\");\n"
		       "  const a = document.createElement(\"input\");\n"
		       "  const b = document.createElement(\"input\");\n"
		       "  const c = document.createElement(\"input\");\n"
		       "  a.dataset.field = \"on\"; a.dataset.ftype = \"boolean\"; a.checked = true;\n"
		       "  b.dataset.field = \"n\"; b.dataset.ftype = \"integer\"; b.value = \"7\";\n"
		       "  c.dataset.field = \"l\"; c.dataset.ftype = \"array\";\n"
		       "  c.value = \"a, b ,, c\";\n"
		       "  f.appendChild(a); f.appendChild(b); f.appendChild(c);\n"
		       "  return JSON.stringify(generatedFormBody(f));\n"
		       "})()",
		       "{\"on\":true,\"n\":7,\"l\":[\"a\",\"b\",\"c\"]}");

		/*
		 * And openForm() itself, which is in form.js for this reason.
		 *
		 * A form that opens EMPTY is the failure to guard against, and
		 * it is not hypothetical: the first draft built the fields and
		 * then called openModal(), which begins by calling
		 * closeModal(), which empties the form -- so every form would
		 * have opened with nothing in it. Nothing caught that; it was
		 * found by reading. The stub reproduces the clearing
		 * faithfully (textContent is an accessor above), so this
		 * assertion fails if the order is ever swapped back.
		 */
		expect(ctx, "a form opens with its one field and its button",
		       "(() => {\n"
		       "  openForm(\"createNtpServer\", { title: \"T\", submit: \"Register\" });\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  return f.children.map((c) => c.tag).join(\",\");\n"
		       "})()",
		       "label,p,button");
		expect(ctx, "the modal was asked to open with the authored title",
		       "globalThis.opened.id + \"/\" + globalThis.opened.title",
		       "generated-form/T");
		expect(ctx, "the button carries the authored words",
		       "(() => {\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  return f.children[f.children.length - 1].textContent;\n"
		       "})()",
		       "Register");
		expect(ctx, "the field's hint is the contract's own description",
		       "(() => {\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  return f.children[1].textContent.slice(0, 24);\n"
		       "})()",
		       "An already-running conta");
	}

	JS_FreeContext(ctx);
	JS_FreeRuntime(rt);
	if (g_fail == 0)
		printf("WEB FORM RESULT: PASS\n");
	return g_fail;
}
