/*
 * test_web_syntax -- the dashboard's JavaScript must parse (#340).
 *
 * Every other surface this project ships is read by a compiler before
 * it reaches a host: cixd, cixctl, the tests and the recipes all go
 * through tcc. web/*.js went through nothing. On 2026-09-08 a dangling
 * `else`, left behind when a refactor removed one arm of an if/else,
 * shipped and took the ENTIRE web UI down on a deployed host:
 *
 *     app.js:2967 Uncaught SyntaxError: Unexpected token 'else'
 *
 * A file that does not parse runs no script at all, so that is a blank
 * dashboard rather than one broken feature -- and it was found by the
 * owner opening the page, which is the wrong way to find it.
 *
 * WHY A REAL PARSER. A textual check was considered and rejected
 * (#340): the broken shape was an `else` whose preceding token is `;`,
 * perfectly legal after a braceless `if`, and this file uses braceless
 * `if` freely. Telling those apart needs a parser, not a heuristic, and
 * a gate with false positives is worse than no gate. So this links
 * quickjs and asks it to COMPILE each file without running it --
 * JS_EVAL_FLAG_COMPILE_ONLY, which parses and generates bytecode and
 * executes none of it. Nothing in the dashboard runs here.
 *
 * `make web-syntax` does the same with node in the dev sandbox. This is
 * the half that runs in SELFTESTS, inside a build container on the box,
 * where node is not packaged and building it would be a V8 compile.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quickjs.h"

static int g_fail;

static char *read_file(const char *path, size_t *out_len)
{
	FILE *f = fopen(path, "rb");
	char *buf;
	long n;

	if (f == NULL)
		return NULL;
	if (fseek(f, 0, SEEK_END) != 0 || (n = ftell(f)) < 0) {
		fclose(f);
		return NULL;
	}
	rewind(f);
	buf = malloc((size_t)n + 1);
	if (buf == NULL) {
		fclose(f);
		return NULL;
	}
	if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
		free(buf);
		fclose(f);
		return NULL;
	}
	fclose(f);
	buf[n] = '\0';
	*out_len = (size_t)n;
	return buf;
}

/*
 * 0 when the source parses. The message is the engine's own, including
 * its line number -- the point of using a parser is that its complaint
 * names the place.
 */
static int parses(JSContext *ctx, const char *src, size_t len, const char *name, char *err,
                  size_t err_size)
{
	JSValue v = JS_Eval(ctx, src, len, name, JS_EVAL_TYPE_GLOBAL | JS_EVAL_FLAG_COMPILE_ONLY);
	JSValue exc;
	const char *msg;

	err[0] = '\0';
	if (!JS_IsException(v)) {
		JS_FreeValue(ctx, v);
		return 0;
	}
	exc = JS_GetException(ctx);
	msg = JS_ToCString(ctx, exc);
	snprintf(err, err_size, "%s", msg != NULL ? msg : "(no message)");
	if (msg != NULL)
		JS_FreeCString(ctx, msg);
	JS_FreeValue(ctx, exc);
	JS_FreeValue(ctx, v);
	return -1;
}

/*
 * A gate that has never rejected anything is a gate nobody has tested.
 * These two run before the real files: the broken one is the SHAPE that
 * caused the outage -- an `else` with no `if` to attach to -- and the
 * good one is there so a parser that rejected everything would fail
 * here rather than look like a pass.
 */
static void self_check(JSContext *ctx)
{
	char err[512];

	if (parses(ctx, "function f(a) { if (a) g(); else h(); }", 38, "<good>", err, sizeof(err)) !=
	    0) {
		fprintf(stderr, "FAIL: self-check: valid JavaScript was rejected: %s\n", err);
		g_fail = 1;
	}
	if (parses(ctx, "function f(a) { if (a) g(); else h(); else }", 43, "<bad>", err,
	           sizeof(err)) == 0) {
		fprintf(stderr, "FAIL: self-check: a dangling `else` was ACCEPTED -- this gate "
		                "would not have caught the outage it was written for\n");
		g_fail = 1;
	}
}

int main(int argc, char **argv)
{
	static const char *const files[] = { "web/app.js", "web/api.js" };
	JSRuntime *rt = JS_NewRuntime();
	JSContext *ctx;
	int i, n;

	if (rt == NULL) {
		fprintf(stderr, "FAIL: could not create a JS runtime\n");
		return 1;
	}
	ctx = JS_NewContext(rt);
	if (ctx == NULL) {
		fprintf(stderr, "FAIL: could not create a JS context\n");
		JS_FreeRuntime(rt);
		return 1;
	}

	self_check(ctx);

	n = argc > 1 ? argc - 1 : (int)(sizeof(files) / sizeof(files[0]));
	for (i = 0; i < n; i++) {
		const char *path = argc > 1 ? argv[i + 1] : files[i];
		char err[512];
		size_t len = 0;
		char *src = read_file(path, &len);

		if (src == NULL) {
			/*
			 * web/api.js is GENERATED by apigen and is not in the
			 * tree until the build has run. Absent is not a pass and
			 * not a failure of this gate -- it is a file that does
			 * not exist yet, said out loud rather than skipped
			 * silently.
			 */
			printf("  %-24s ABSENT (not checked)\n", path);
			continue;
		}
		if (parses(ctx, src, len, path, err, sizeof(err)) != 0) {
			fprintf(stderr, "FAIL: %s does not parse: %s\n", path, err);
			fprintf(stderr,
			        "      A file that does not parse runs NO script at all, so this "
			        "would ship a blank dashboard, not one broken feature.\n");
			g_fail = 1;
		} else {
			printf("  %-24s parses\n", path);
		}
		free(src);
	}

	JS_FreeContext(ctx);
	JS_FreeRuntime(rt);
	if (g_fail) {
		fprintf(stderr, "test_web_syntax: FAILED\n");
		return 1;
	}
	printf("test_web_syntax: the dashboard parses\n");
	return 0;
}
