/*
 * test_web_form -- the generated form is RUN, not just parsed.
 *
 * `web/form.js` turns a field the contract describes into the one
 * control that field's own constraints call for (ADR-0338, #595), and
 * until this existed the only gate over it was `test_web_syntax`, which
 * proves a file parses. That distinction is not academic here: three
 * releases in one day shipped a `web/api.js` that parsed every
 * assertion put to it and would not load in a browser (#594), and the
 * check that caught them was the one that handed the file to a real
 * engine.
 *
 * So this hands the engine the real generated `web/api.js` and the real
 * `web/form.js`, over a DOM small enough to write down, and asserts
 * what an operator would otherwise have to open the dashboard to see:
 *
 *   - a field the contract marks `format: password` renders obscured,
 *     which is the whole reason those eight fields carry it;
 *   - an `enum` renders as a select carrying exactly its own values,
 *     in contract order;
 *   - a numeric field carries the contract's own minimum and maximum,
 *     so a form refuses what the daemon would refuse;
 *   - an empty optional field is OMITTED from the body rather than sent
 *     as "", because every partial-update endpoint here reads an absent
 *     key as "leave it alone";
 *   - a boolean is a checkbox and arrives as a boolean, not as "on";
 *   - a field the contract marks `x-cix-ui: textarea`, and any field
 *     typed `object`, renders multi-line -- and every `ui` value in
 *     the whole generated surface is one this renderer knows, which
 *     is the half of that pair apigen cannot gate;
 *   - a free-form object round-trips as JSON and a mistyped one is
 *     refused by name rather than sent;
 *   - a `fixed` field -- the key of an upsert addressing something
 *     that already exists -- renders read-only and is still SENT.
 *
 * The DOM shim is deliberately the smallest thing form.js actually
 * uses. It is not a browser, and a test that needed more of one would
 * be a sign the renderer had grown a dependency it should not have.
 */
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quickjs.h"

_Static_assert(JS_LIMB_BITS == 32,
               "quickjs.h took the __int128 arm under this compiler, but the library is "
               "built with -U__SIZEOF_INT128__ on the other one -- see "
               "recipes/package/quickjs/2026-06-04-3");

static int g_fail;

static void fail(const char *fmt, ...)
{
	va_list ap;

	fprintf(stderr, "FAIL: ");
	va_start(ap, fmt);
	vfprintf(stderr, fmt, ap);
	va_end(ap);
	fprintf(stderr, "\n");
	g_fail = 1;
}

static char *read_file(const char *path, size_t *out_len)
{
	FILE *f = fopen(path, "rb");
	long n;
	char *buf;

	if (f == NULL)
		return NULL;
	if (fseek(f, 0, SEEK_END) != 0) {
		fclose(f);
		return NULL;
	}
	n = ftell(f);
	if (n < 0 || fseek(f, 0, SEEK_SET) != 0) {
		fclose(f);
		return NULL;
	}
	buf = malloc((size_t)n + 1);
	if (buf == NULL) {
		fclose(f);
		return NULL;
	}
	if (fread(buf, 1, (size_t)n, f) != (size_t)n) {
		free(buf);
		fclose(f);
		return NULL;
	}
	buf[n] = '\0';
	fclose(f);
	if (out_len != NULL)
		*out_len = (size_t)n;
	return buf;
}

/* Evaluates one file, reporting what the engine said about it. */
static int run_file(JSContext *ctx, const char *path)
{
	size_t len = 0;
	char *src = read_file(path, &len);
	JSValue v;
	int bad;

	if (src == NULL) {
		fail("could not read %s -- api.js is generated by apigen and is a "
		     "prerequisite of the build, so an absent one is a broken build and not "
		     "a reason to skip this",
		     path);
		return -1;
	}
	v = JS_Eval(ctx, src, len, path, JS_EVAL_TYPE_GLOBAL);
	bad = JS_IsException(v);
	if (bad) {
		JSValue e = JS_GetException(ctx);
		const char *msg = JS_ToCString(ctx, e);

		fail("%s threw while loading: %s", path, msg != NULL ? msg : "(no message)");
		if (msg != NULL)
			JS_FreeCString(ctx, msg);
		JS_FreeValue(ctx, e);
	}
	JS_FreeValue(ctx, v);
	free(src);
	return bad ? -1 : 0;
}

/*
 * The DOM, as far as form.js reaches into it: an element with a
 * mutable property bag, children, a dataset, and querySelectorAll over
 * the one attribute the body collector selects on.
 */
static const char *const DOM_SHIM =
    /*
     * The six globals form.js expects app.js to have defined, stubbed
     * to record rather than act. `openModal` empties the form first,
     * exactly as the real one does by calling closeModal() -- which is
     * the whole reason this stub is worth having: the first draft of
     * openForm() built its fields and THEN opened the modal, so every
     * form would have opened empty, and nothing but reading the code
     * caught it.
     */
    "globalThis.opened = null;\n"
    "globalThis.openModal = (id, title) => {\n"
    "  globalThis.opened = { id: id, title: title };\n"
    "  document.getElementById(\"generated-form\").textContent = \"\";\n"
    "};\n"
    "globalThis.sessionMay = () => true;\n"
    "globalThis.sessionRefusal = () => \"no\";\n"
    "globalThis.status_said = null;\n"
    "globalThis.showStatus = (m) => { globalThis.status_said = m; };\n"
    "globalThis.runRefreshers = async () => {};\n"
    "globalThis.refreshersForView = () => [];\n"
    /*
     * Records rather than acts: the real one installs a blur listener,
     * and what matters here is WHICH fields it is applied to -- the
     * decision is the contract's `format: hostname`, and the site
     * knowledge it needs is app.js's.
     */
    "globalThis.qualifyHostname = (el) => { el.dataset.qualified = \"1\"; };\n"
    "globalThis.document = {\n"
    "  getElementById(id) {\n"
    "    if (this._byId === undefined)\n"
    "      this._byId = {};\n"
    "    if (this._byId[id] === undefined) {\n"
    "      this._byId[id] = this.createElement(\"form\");\n"
    "      this._byId[id].id = id;\n"
    "    }\n"
    "    return this._byId[id];\n"
    "  },\n"
    "  querySelector() { return null; },\n"
    "  createElement(tag) {\n"
    "    const el = {\n"
    "      tag: tag, dataset: {}, children: [],\n"
    "      appendChild(c) { this.children.push(c); },\n"
    "      querySelectorAll(sel) {\n"
    "        const out = [];\n"
    "        const walk = (n) => {\n"
    "          for (const c of n.children) {\n"
    "            if (sel === \"[data-field]\" && c.dataset.field !== undefined)\n"
    "              out.push(c);\n"
    "            walk(c);\n"
    "          }\n"
    "        };\n"
    "        walk(this);\n"
    "        return out;\n"
    "      },\n"
    "    };\n"
    /*
     * textContent is an ACCESSOR, not a field, because the one DOM
     * behaviour the renderer depends on is that assigning "" removes
     * every child. A plain property would record the assignment and
     * keep the children, which would make this shim agree with a bug
     * instead of catching it.
     */
    "    let text = \"\";\n"
    "    Object.defineProperty(el, \"textContent\", {\n"
    "      get() { return text; },\n"
    "      set(v) { text = v; if (v === \"\") this.children.length = 0; },\n"
    "    });\n"
    "    return el;\n"
    "  },\n"
    "};\n";

/* Runs an expression and returns its value as a freshly allocated
 * string, or NULL having already reported why not. */
static char *eval_str(JSContext *ctx, const char *expr, const char *what)
{
	JSValue v = JS_Eval(ctx, expr, strlen(expr), what, JS_EVAL_TYPE_GLOBAL);
	const char *s;
	char *copy = NULL;

	if (JS_IsException(v)) {
		JSValue e = JS_GetException(ctx);
		const char *msg = JS_ToCString(ctx, e);

		fail("%s threw: %s", what, msg != NULL ? msg : "(no message)");
		if (msg != NULL)
			JS_FreeCString(ctx, msg);
		JS_FreeValue(ctx, e);
		JS_FreeValue(ctx, v);
		return NULL;
	}
	s = JS_ToCString(ctx, v);
	if (s != NULL) {
		copy = strdup(s);
		JS_FreeCString(ctx, s);
	}
	JS_FreeValue(ctx, v);
	return copy;
}

static void expect(JSContext *ctx, const char *what, const char *expr, const char *want)
{
	char *got = eval_str(ctx, expr, what);

	if (got == NULL)
		return;
	if (strcmp(got, want) != 0)
		fail("%s: expected `%s`, got `%s`", what, want, got);
	free(got);
}

int main(void)
{
	JSRuntime *rt = JS_NewRuntime();
	JSValue shim;
	int shim_bad;
	JSContext *ctx;

	if (rt == NULL) {
		fprintf(stderr, "FAIL: could not create a JS runtime\n");
		return 1;
	}
	ctx = JS_NewContext(rt);
	if (ctx == NULL) {
		fprintf(stderr, "FAIL: could not create a JS context\n");
		JS_FreeRuntime(rt);
		return 1;
	}

	/*
	 * The shim's value is FREED, not discarded. Its last statement is
	 * an assignment, so the eval returns the object assigned -- a real
	 * GC object, and leaking it makes JS_FreeRuntime() assert
	 * `list_empty(&rt->gc_obj_list)` at teardown. That is what gate 535
	 * reported: every assertion in this file passed and the runtime
	 * then refused to shut down, which reads as a test failure and is
	 * a leak in the test.
	 */
	shim = JS_Eval(ctx, DOM_SHIM, strlen(DOM_SHIM), "<dom>", JS_EVAL_TYPE_GLOBAL);
	shim_bad = JS_IsException(shim);
	JS_FreeValue(ctx, shim);
	if (shim_bad)
		fail("the DOM shim itself does not load");
	else if (run_file(ctx, "web/api.js") == 0 && run_file(ctx, "web/form.js") == 0) {
		/*
		 * Each assertion names a REAL field of a REAL schema, so the
		 * contract and the renderer are checked against each other
		 * rather than against a fixture that could drift from both.
		 */
		expect(ctx, "a field name reads as a label", "fieldLabel(\"prefix_len\")",
		       "Prefix len");

		/* postLogin's password: the first reason `format: password`
		 * exists in the contract at all. */
		expect(ctx, "a password field is obscured",
		       "fieldControl(CIX_API.FIELDS.postLoginRequest.find("
		       "(f) => f.name === \"password\")).type",
		       "password");
		expect(ctx, "a plain string field is not",
		       "fieldControl(CIX_API.FIELDS.postLoginRequest.find("
		       "(f) => f.name === \"username\")).type",
		       "text");

		/* NetworkCreateRequest's prefix_len carries minimum: 8 and
		 * maximum: 30, which no hand-written form carried. */
		expect(ctx, "a numeric field carries the contract's minimum",
		       "fieldControl(CIX_API.FIELDS.NetworkCreateRequest.find("
		       "(f) => f.name === \"prefix_len\")).min",
		       "8");
		expect(ctx, "a numeric field carries the contract's maximum",
		       "fieldControl(CIX_API.FIELDS.NetworkCreateRequest.find("
		       "(f) => f.name === \"prefix_len\")).max",
		       "30");

		/*
		 * The NTP binding's container carries a pattern, moved into
		 * the contract when its hand-written form was retired.
		 *
		 * The hyphen is `\-` and that is load-bearing, not a style:
		 * a browser compiles this with the regex `v` flag, under
		 * which a bare `-` at the end of a class is a SyntaxError,
		 * and the HTML spec then SKIPS the constraint silently. This
		 * assertion expected the bare form and is what the 487 gate
		 * caught when all 27 patterns were corrected -- which is the
		 * gate working, and a reminder that a mechanical sweep is not
		 * finished until its dependents have been grepped for.
		 */
		expect(ctx, "a string field carries the contract's pattern",
		       "fieldControl(CIX_API.FIELDS.NtpServerBindingCreateRequest.find("
		       "(f) => f.name === \"container\")).pattern",
		       "^[A-Za-z0-9_\\-]+$");
		expect(ctx, "a required field is required",
		       "String(fieldControl(CIX_API.FIELDS.NtpServerBindingCreateRequest.find("
		       "(f) => f.name === \"container\")).required)",
		       "true");

		/* An enum becomes a select carrying its own values, in order,
		 * and the one written across two lines in the contract is the
		 * one to check (#602). */
		expect(ctx, "an enum becomes a select",
		       "fieldControl(CIX_API.FIELDS.SourceCatalogueEntry.find("
		       "(f) => f.name === \"stage\")).tag",
		       "select");
		expect(ctx, "a select carries every value the contract lists",
		       "fieldControl(CIX_API.FIELDS.SourceCatalogueEntry.find("
		       "(f) => f.name === \"stage\")).children.map((o) => o.value).join(\",\")",
		       "discover,resolve,authenticate,author,fetch,unpack,build,install,publish,"
		       "roll,deploy,acquire,assemble,stage,verify");

		/*
		 * And the body. An empty optional is omitted, an empty
		 * REQUIRED one is sent (so the daemon's own refusal is what
		 * the operator sees, rather than the form quietly dropping a
		 * key the endpoint demands), a boolean is a boolean, and a
		 * comma-separated list is an array.
		 */
		expect(ctx, "an empty optional field is omitted from the body",
		       "(() => {\n"
		       "  const f = document.createElement(\"form\");\n"
		       "  const a = document.createElement(\"input\");\n"
		       "  const b = document.createElement(\"input\");\n"
		       "  a.dataset.field = \"kept\"; a.dataset.ftype = \"string\"; a.value = \"x\";\n"
		       "  b.dataset.field = \"gone\"; b.dataset.ftype = \"string\"; b.value = \"\";\n"
		       "  f.appendChild(a); f.appendChild(b);\n"
		       "  return JSON.stringify(generatedFormBody(f));\n"
		       "})()",
		       "{\"kept\":\"x\"}");
		expect(ctx, "a checkbox arrives as a boolean and a list as an array",
		       "(() => {\n"
		       "  const f = document.createElement(\"form\");\n"
		       "  const a = document.createElement(\"input\");\n"
		       "  const b = document.createElement(\"input\");\n"
		       "  const c = document.createElement(\"input\");\n"
		       "  a.dataset.field = \"on\"; a.dataset.ftype = \"boolean\"; a.checked = true;\n"
		       "  b.dataset.field = \"n\"; b.dataset.ftype = \"integer\"; b.value = \"7\";\n"
		       "  c.dataset.field = \"l\"; c.dataset.ftype = \"array\";\n"
		       "  c.value = \"a, b ,, c\";\n"
		       "  f.appendChild(a); f.appendChild(b); f.appendChild(c);\n"
		       "  return JSON.stringify(generatedFormBody(f));\n"
		       "})()",
		       "{\"on\":true,\"n\":7,\"l\":[\"a\",\"b\",\"c\"]}");

		/*
		 * And openForm() itself, which is in form.js for this reason.
		 *
		 * A form that opens EMPTY is the failure to guard against, and
		 * it is not hypothetical: the first draft built the fields and
		 * then called openModal(), which begins by calling
		 * closeModal(), which empties the form -- so every form would
		 * have opened with nothing in it. Nothing caught that; it was
		 * found by reading. The stub reproduces the clearing
		 * faithfully (textContent is an accessor above), so this
		 * assertion fails if the order is ever swapped back.
		 */
		expect(ctx, "a form opens with its one field and its button",
		       "(() => {\n"
		       "  openForm(\"createNtpServer\", { title: \"T\", submit: \"Register\" });\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  return f.children.map((c) => c.tag).join(\",\");\n"
		       "})()",
		       "label,button");
		/*
		 * `label,button` and not `label,p,button`: the hint lives
		 * INSIDE its label, so a field is one grid cell containing
		 * name, control and explanation. It was a form child until
		 * the first real modal was rendered, where it landed in the
		 * next grid column and read as a peer of the field rather
		 * than as its explanation -- and this assertion, written
		 * against the old shape, is what the 486 gate caught.
		 */
		expect(ctx, "and the field's own hint is inside its label",
		       "(() => {\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  const label = f.children[0];\n"
		       "  return label === undefined ? \"no field\"\n"
		       "    : label.children.map((c) => c.tag).join(\",\");\n"
		       "})()",
		       "input,p");
		/*
		 * These three read what the call above produced, so each
		 * answers "not opened" or "no such child" rather than throwing
		 * on a null or an empty array. A dependent assertion that
		 * throws reports a TypeError about its own expression and
		 * hides the failure it was downstream of -- which is one more
		 * eleven-minute cycle to work out that the first assertion was
		 * the real one.
		 */
		expect(ctx, "the modal was asked to open with the authored title",
		       "globalThis.opened === null ? \"not opened\"\n"
		       "  : globalThis.opened.id + \"/\" + globalThis.opened.title",
		       "generated-form/T");
		expect(ctx, "the button carries the authored words",
		       "(() => {\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  const last = f.children[f.children.length - 1];\n"
		       "  return last === undefined ? \"no children\" : last.textContent;\n"
		       "})()",
		       "Register");
		expect(ctx, "the field's hint is the contract's own description",
		       "(() => {\n"
		       "  const f = document.getElementById(\"generated-form\");\n"
		       "  const label = f.children[0];\n"
		       "  const hint = label === undefined ? undefined : label.children[1];\n"
		       "  return hint === undefined ? \"no hint\"\n"
		       "    : hint.textContent.slice(0, 24);\n"
		       "})()",
		       "An already-running conta");

		/*
		 * fieldText: one value, as text, decided by its field.
		 *
		 * The counted inconsistency this ends: before it, a boolean
		 * read "yes"/"no" 16 times in app.js, "enabled"/"disabled" 4
		 * and "true"/"false" once, while an absent value read "-" 67
		 * times, "none" 41, "unknown" 12, "unset" 4 and an em dash 3.
		 *
		 * The last case is the one a naive version gets wrong: an
		 * absent boolean whose schema declares a default is NOT
		 * unknown. app.js has `s.enabled === false ? "no" : "yes"`
		 * for exactly that, and it is correct.
		 */
		expect(ctx, "a true boolean reads one way everywhere",
		       "fieldText({ type: \"boolean\" }, true)", "yes");
		expect(ctx, "a false boolean too",
		       "fieldText({ type: \"boolean\" }, false)", "no");
		expect(ctx, "an absent value is one em dash, not five spellings",
		       "fieldText({ type: \"string\" }, undefined)", "—");
		expect(ctx, "an empty string is absent, not empty-looking",
		       "fieldText({ type: \"string\" }, \"\")", "—");
		expect(ctx, "an absent boolean takes the contract's own default",
		       "fieldText({ type: \"boolean\", fallback: true }, undefined)", "yes");
		expect(ctx, "and reports absent when the contract declares none",
		       "fieldText({ type: \"boolean\" }, undefined)", "—");
		expect(ctx, "an array joins", "fieldText({ type: \"array\" }, [\"a\", \"b\"])",
		       "a, b");

		/*
		 * A pattern must survive YAML, apigen and the JS writer and
		 * still be the regex the contract meant (#596).
		 *
		 * `hosts_path` is the first one with a backslash in it, and
		 * that is where the chain can break silently: a DOUBLE-quoted
		 * YAML scalar would have to write `\\.` for one backslash,
		 * apigen reads the raw bytes rather than parsing YAML escapes,
		 * and `emit_js_string()` then doubles each one again -- so the
		 * browser would compile `\\.` and demand a literal backslash.
		 * The contract uses a single-quoted scalar for that reason.
		 * Compiling it here and trying real paths is the only check
		 * that can tell the two apart.
		 */
		expect(ctx, "a path pattern accepts an absolute path",
		       "String(new RegExp(CIX_API.FIELDS.DnsServerBindingCreateRequest"
		       ".find((f) => f.name === \"hosts_path\").pattern)"
		       ".test(\"/etc/dnsmasq-hosts\"))",
		       "true");
		expect(ctx, "and rejects a relative one",
		       "String(new RegExp(CIX_API.FIELDS.DnsServerBindingCreateRequest"
		       ".find((f) => f.name === \"hosts_path\").pattern)"
		       ".test(\"etc/dnsmasq-hosts\"))",
		       "false");
		expect(ctx, "and rejects one containing ..",
		       "String(new RegExp(CIX_API.FIELDS.DnsServerBindingCreateRequest"
		       ".find((f) => f.name === \"hosts_path\").pattern)"
		       ".test(\"/etc/../shadow\"))",
		       "false");
		expect(ctx, "an empty array is absent",
		       "fieldText({ type: \"array\" }, [])", "—");

		/*
		 * renderTableRows over the real Network schema, with the four
		 * columns the hand-written table actually shows -- the authored
		 * part -- and every cell's text derived.
		 */
		expect(ctx, "a table's cells come from the schema's own types",
		       "(() => {\n"
		       "  const b = document.createElement(\"tbody\");\n"
		       "  renderTableRows(b, \"Network\",\n"
		       "    [{ name: \"mgmt\", subnet: \"10.0.0.0\", prefix_len: 24,\n"
		       "       address: \"\", management: true, interfaces: [] }],\n"
		       "    [\"name\", \"subnet\", \"prefix_len\", \"address\", \"management\",\n"
		       "     \"interfaces\"], \"none\");\n"
		       "  return b.children[0].children.map((c) => c.textContent).join(\"|\");\n"
		       "})()",
		       "mgmt|10.0.0.0|24|—|yes|—");
		expect(ctx, "an empty table says so once, across the right span",
		       "(() => {\n"
		       "  const b = document.createElement(\"tbody\");\n"
		       "  renderTableRows(b, \"Network\", [], [\"name\", \"subnet\"], \"No networks\");\n"
		       "  const cell = b.children[0].children[0];\n"
		       "  return cell.textContent + \"/\" + cell.colSpan + \"/\" + cell.className;\n"
		       "})()",
		       "No networks/2/empty");

		/* renderDetailRows: schema order, every field, read-only
		 * included -- a detail page is where "the daemon reports this
		 * and you cannot set it" belongs. */
		expect(ctx, "a detail page shows every field in schema order",
		       "(() => {\n"
		       "  const b = document.createElement(\"tbody\");\n"
		       "  renderDetailRows(b, \"Network\",\n"
		       "    { name: \"mgmt\", subnet: \"10.0.0.0\", prefix_len: 24,\n"
		       "      has_address: false, address: \"\", management: true });\n"
		       "  return b.children.map((r) => r.children[0].textContent).join(\",\");\n"
		       "})()",
		       "Name,Subnet,Prefix len,Has address,Address,Management,Interfaces");

		/*
		 * ---- the multi-line control, and the two ways a field asks
		 * for one (#596) ----
		 *
		 * A STRING asks explicitly, with `x-cix-ui: textarea`, because
		 * nothing in JSON Schema distinguishes one line from twenty
		 * and an image recipe is twenty. An OBJECT needs no annotation
		 * and is derived: a free-form object is typed as JSON, and a
		 * one-line input is never the right control for JSON.
		 *
		 * Both name a real field of a real schema, so a contract that
		 * loses the annotation fails here rather than rendering a
		 * recipe document into a 15rem text box.
		 */
		expect(ctx, "an x-cix-ui string field is a textarea",
		       "fieldControl(CIX_API.FIELDS.addImageRecipeRequest.find("
		       "(f) => f.name === \"content\")).tag",
		       "textarea");
		expect(ctx, "and it is tall enough to hold a document",
		       "String(fieldControl(CIX_API.FIELDS.addImageRecipeRequest.find("
		       "(f) => f.name === \"content\")).rows)",
		       "12");
		expect(ctx, "an object field is a textarea with no annotation at all",
		       "fieldControl(CIX_API.FIELDS.applyDeploymentRequest.find("
		       "(f) => f.name === \"secrets\")).tag",
		       "textarea");
		expect(ctx, "the contract still asks for one, in one place",
		       "String(CIX_API.FIELDS.addImageRecipeRequest.find("
		       "(f) => f.name === \"content\").ui)",
		       "textarea");
		/*
		 * EVERY `ui` value in the whole generated surface, against the
		 * one this renderer knows. apigen refuses an unknown value at
		 * generation; this is the other half of that pair -- it fails
		 * if the renderer ever loses the branch while the contract
		 * keeps asking for it, which apigen cannot see.
		 */
		expect(ctx, "the only control the contract ever asks for is one this builds",
		       "(() => {\n"
		       "  const seen = new Set();\n"
		       "  for (const name of Object.keys(CIX_API.FIELDS))\n"
		       "    for (const f of CIX_API.FIELDS[name])\n"
		       "      if (f.ui !== undefined) seen.add(f.ui);\n"
		       "  return [...seen].sort().join(\",\");\n"
		       "})()",
		       "textarea");

		/*
		 * A free-form object round-trips: shown as indented JSON,
		 * read back as an object. The two halves are written in
		 * different functions and a form opened on a resource and
		 * submitted unchanged must send what it was given.
		 */
		expect(ctx, "an object field is shown as JSON and read back as an object",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.applyDeploymentRequest.find(\n"
		       "    (x) => x.name === \"secrets\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  setFieldValue(el, f, { KEY: \"real\" });\n"
		       "  form.appendChild(el);\n"
		       "  return JSON.stringify(generatedFormBody(form));\n"
		       "})()",
		       "{\"secrets\":{\"KEY\":\"real\"}}");
		expect(ctx, "an untouched optional object field sends nothing",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.applyDeploymentRequest.find(\n"
		       "    (x) => x.name === \"secrets\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  el.value = \"\\n  \";\n"
		       "  form.appendChild(el);\n"
		       "  return JSON.stringify(generatedFormBody(form));\n"
		       "})()",
		       "{}");
		/*
		 * And a mistyped one REFUSES, with the field named. It throws
		 * because the one submit listener collects the body inside its
		 * own try/catch: the message reaches the status line and the
		 * modal stays open with the text still in it, which is the
		 * whole point when the text is what was mistyped.
		 */
		expect(ctx, "invalid JSON is refused, naming the field",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.applyDeploymentRequest.find(\n"
		       "    (x) => x.name === \"secrets\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  el.value = \"{oops\";\n"
		       "  form.appendChild(el);\n"
		       "  try { generatedFormBody(form); return \"accepted\"; }\n"
		       "  catch (e) { return e.message.slice(0, 27); }\n"
		       "})()",
		       "Secrets must be valid JSON:");
		expect(ctx, "and so is a bare value that is not an object",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.applyDeploymentRequest.find(\n"
		       "    (x) => x.name === \"secrets\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  el.value = \"7\";\n"
		       "  form.appendChild(el);\n"
		       "  try { generatedFormBody(form); return \"accepted\"; }\n"
		       "  catch (e) { return e.message; }\n"
		       "})()",
		       "Secrets must be a JSON object, not a bare value");

		/*
		 * ---- `fixed`: the key of an upsert, shown and not editable ----
		 *
		 * addImageRecipe is one operation for a create and for an
		 * edit, and on an edit its `name` names something that already
		 * exists -- typing over it would not rename anything, it would
		 * address a different image. So it renders read-only and is
		 * STILL SENT, which is the part a flag called "disabled" would
		 * have got wrong.
		 */
		expect(ctx, "a form opened on an existing resource shows its key, locked",
		       "(() => {\n"
		       "  openForm(\"addImageRecipe\", { title: \"Edit\", submit: \"Save\",\n"
		       "    fixed: { name: \"jump\" }, values: { content: \"{}\" } });\n"
		       "  const form = document.getElementById(\"generated-form\");\n"
		       "  const el = form.children[0].children[0];\n"
		       "  return el.tag + \"/\" + el.value + \"/\" + el.readOnly;\n"
		       "})()",
		       "input/jump/true");
		expect(ctx, "and sends it, because the operation needs it",
		       "JSON.stringify(generatedFormBody("
		       "document.getElementById(\"generated-form\")))",
		       "{\"name\":\"jump\",\"content\":\"{}\"}");
		/*
		 * `format: hostname` gets the bare-label convenience, and a
		 * field that is not a hostname does not. This was wired to
		 * two element ids before, so only those two had it -- a
		 * convenience attached to an id cannot reach the next field
		 * of the same kind that anyone adds.
		 */
		expect(ctx, "a hostname field gets the bare-label qualifier",
		       "String(fieldControl(CIX_API.FIELDS.DnsRecordCreateRequest.find("
		       "(f) => f.name === \"name\")).dataset.qualified)",
		       "1");
		expect(ctx, "and an ordinary string field does not",
		       "String(fieldControl(CIX_API.FIELDS.DnsRecordCreateRequest.find("
		       "(f) => f.name === \"ip\")).dataset.qualified)",
		       "undefined");
		expect(ctx, "a hostname's pattern accepts a dotted name",
		       "String(new RegExp(CIX_API.FIELDS.DnsRecordCreateRequest"
		       ".find((f) => f.name === \"name\").pattern).test(\"db.home.arpa\"))",
		       "true");
		/* The daemon's own rule, not the RFC's: dns_name_is_valid()
		 * checks the charset and the label length and nothing else,
		 * so a leading hyphen is accepted and the contract says so --
		 * a stricter pattern would make the form refuse a name the
		 * daemon takes. */
		expect(ctx, "and a leading hyphen, which the daemon accepts",
		       "String(new RegExp(CIX_API.FIELDS.DnsRecordCreateRequest"
		       ".find((f) => f.name === \"name\").pattern).test(\"-db.home.arpa\"))",
		       "true");
		expect(ctx, "while an empty label is refused",
		       "String(new RegExp(CIX_API.FIELDS.DnsRecordCreateRequest"
		       ".find((f) => f.name === \"name\").pattern).test(\"db..arpa\"))",
		       "false");
		expect(ctx, "and an underscore, which the charset excludes",
		       "String(new RegExp(CIX_API.FIELDS.DnsRecordCreateRequest"
		       ".find((f) => f.name === \"name\").pattern).test(\"db_1.arpa\"))",
		       "false");

		/*
		 * An array's ITEM type, which a comma-separated list does not
		 * carry by itself.
		 *
		 * `secondary_groups` is `items: integer`, and the body used to
		 * carry `["10001","10002"]` -- which the daemon reads with
		 * json_as_number() on a JSON string, so every gid arrived as
		 * 0 and the user landed in no secondary group. Silent and
		 * wrong rather than refused, which is why it is gated.
		 */
		expect(ctx, "a numeric list arrives as numbers, not strings",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.LdapUserCreateRequest.find(\n"
		       "    (x) => x.name === \"secondary_groups\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  el.value = \"10001, 10002\";\n"
		       "  form.appendChild(el);\n"
		       "  return JSON.stringify(generatedFormBody(form));\n"
		       "})()",
		       "{\"secondary_groups\":[10001,10002]}");
		expect(ctx, "and a list of strings still arrives as strings",
		       "(() => {\n"
		       "  const f = CIX_API.FIELDS.PkiCertCreateRequest.find(\n"
		       "    (x) => x.name === \"sans\");\n"
		       "  const el = fieldControl(f);\n"
		       "  const form = document.createElement(\"form\");\n"
		       "  el.value = \"a.b, c.d\";\n"
		       "  form.appendChild(el);\n"
		       "  return JSON.stringify(generatedFormBody(form));\n"
		       "})()",
		       "{\"sans\":[\"a.b\",\"c.d\"]}");

		expect(ctx, "the document field of that same form is the wide one",
		       "(() => {\n"
		       "  const form = document.getElementById(\"generated-form\");\n"
		       "  return form.children[1].className + \"/\" +\n"
		       "    form.children[1].children[0].tag;\n"
		       "})()",
		       "wide/textarea");
	}

	JS_FreeContext(ctx);
	JS_FreeRuntime(rt);
	if (g_fail == 0)
		printf("WEB FORM RESULT: PASS\n");
	return g_fail;
}
