/*
 * form.js -- the contract's own description of a request, as controls.
 *
 * GENERATED by nothing; this is the renderer that reads what apigen
 * generates (ADR-0338, #595). It is its own file for one reason: it has
 * no dependency on the dashboard at all beyond `document` and
 * `CIX_API`, which means a test can EXECUTE it rather than only parse
 * it -- `test_web_form` evals this file against a minimal DOM and
 * asserts that a `format: password` field really does produce an
 * obscured input, that an enum really does produce its own options, and
 * that an empty optional field really is omitted from the body.
 *
 * Keeping it inside app.js would have made that impossible: evaluating
 * that file runs a dashboard's worth of module-level wiring against
 * hundreds of element ids, so the only check it can ever have is that
 * it parses -- which is exactly the gap that let three unparseable
 * api.js releases through (#594).
 *
 * app.js owns the SUBMIT listener, and only that, because it is an HTTP
 * request and a status line and neither can be stubbed meaningfully.
 *
 * What this file expects app.js to have defined, which is the whole of
 * its dependency on the dashboard and is deliberately short enough to
 * stub in a test: `openModal`, `sessionMay`, `sessionRefusal`,
 * `showStatus`, `runRefreshers` and `refreshersForView`.
 */
/*
 * ---------- what a request schema becomes ----------
 *
 * One modal panel, built from the operation's own request schema, for
 * every create and edit the dashboard offers.
 *
 * The 36 hand-written forms this replaces re-typed what the contract
 * already states -- field names, types, which are required, which
 * values an enum allows -- and dropped what it states that is hardest
 * to re-type: 174 constraints, which reached the operator as a
 * round-trip 400 instead of as a form that would not submit. So the
 * split is ADR-0338's sixth principle exactly. GENERATED, because two
 * competent people would write it identically from the schema: the
 * fields, their order, their controls, their bounds, their hints.
 * AUTHORED at the call site, because it takes judgement: the modal's
 * title, the three words on its button, which resource list to refresh
 * afterwards, and what to say when it fails.
 *
 * A field's rendering is decided by the field, never by its name -- a
 * `name === "password"` special case here would be the parallel the
 * guidelines forbid, and is why the eight secrets an operator TYPES
 * carry `format: password` in the contract instead.
 */

/* The label a field name reads as. Derived, because the schema already
 * named the field; a hand-written label is the duplication principle 6
 * exists to stop. `prefix_len` reads as "Prefix len", which is plain
 * rather than pretty -- when that is genuinely wrong the fix is the
 * contract's own `x-cix-ui`, never a table here. */
function fieldLabel(name) {
	const words = name.replace(/_/g, " ");

	return words.charAt(0).toUpperCase() + words.slice(1);
}

/*
 * The one control a field's constraints describe.
 *
 * Every branch is a property of the schema and nothing else: options
 * make a select, boolean a checkbox, a numeric type a number input
 * carrying its own minimum and maximum, `format: password` an obscured
 * input, and a string its pattern and maxLength. An array of scalars is
 * a comma-separated text input, the convention the hand-written
 * container form already used for `dns_servers`.
 */
function fieldControl(f) {
	let el;

	if (Array.isArray(f.options) && f.options.length > 0) {
		el = document.createElement("select");
		if (!f.required) {
			const blank = document.createElement("option");

			blank.value = "";
			blank.textContent = "—";
			el.appendChild(blank);
		}
		for (const opt of f.options) {
			const o = document.createElement("option");

			o.value = opt;
			o.textContent = opt;
			el.appendChild(o);
		}
	} else if (f.type === "boolean") {
		el = document.createElement("input");
		el.type = "checkbox";
		if (f.fallback === true)
			el.checked = true;
	} else if (f.type === "integer" || f.type === "number") {
		el = document.createElement("input");
		el.type = "number";
		if (f.minimum !== undefined)
			el.min = String(f.minimum);
		if (f.maximum !== undefined)
			el.max = String(f.maximum);
		if (f.type === "integer")
			el.step = "1";
	} else {
		el = document.createElement("input");
		el.type = f.format === "password" ? "password" : "text";
		if (f.pattern !== undefined)
			el.pattern = f.pattern;
		if (f.maxLength !== undefined)
			el.maxLength = f.maxLength;
	}
	el.id = "gf-" + f.name;
	el.dataset.field = f.name;
	el.dataset.ftype = f.type;
	if (f.required && f.type !== "boolean")
		el.required = true;
	return el;
}

/*
 * What the operator typed, as the request body the schema describes.
 *
 * An empty optional field is OMITTED rather than sent as "", because
 * every partial-update endpoint in this API reads an absent key as
 * "leave it alone" and an empty string as "set it to empty" -- sending
 * the second for the first is how a generated form would quietly clear
 * a field nobody touched.
 */
function generatedFormBody(form) {
	const body = {};

	for (const el of form.querySelectorAll("[data-field]")) {
		const name = el.dataset.field;
		const type = el.dataset.ftype;

		if (type === "boolean") {
			body[name] = el.checked;
			continue;
		}
		if (el.value === "" && !el.required)
			continue;
		if (type === "integer" || type === "number") {
			body[name] = Number(el.value);
			continue;
		}
		if (type === "array") {
			body[name] = el.value
				.split(",")
				.map((s) => s.trim())
				.filter((s) => s.length > 0);
			continue;
		}
		body[name] = el.value;
	}
	return body;
}

/* The two things a submit needs that are not in the form: what to
 * refresh afterwards and what to say if it fails. Authored per call
 * site, held here because the one submit listener reads them. */
let generatedFormAfter = null;
let generatedFormFailed = "";

/*
 * The default `after`: whatever keeps the view the operator is looking
 * at honest.
 *
 * Every screen already declares its own refreshers in VIEW_REFRESHERS,
 * and both the poll loop and the tab bar run them that way -- so a
 * generated form needs no per-form refresh wiring at all. Each of the
 * 36 hand-written forms carried its own copy of that call, which is one
 * more thing that could be forgotten on the 37th.
 */
async function refreshVisibleView() {
	const view = document.querySelector(".view:not([hidden])");

	if (view !== null)
		await runRefreshers(refreshersForView(view.id));
}

/*
 * Open the generated form for one operation.
 *
 * opts.title    the modal's heading                (authored)
 * opts.submit   the words on the button            (authored)
 * opts.args     the operation's path parameters, in contract order
 * opts.after    what to refresh once it succeeds   (authored)
 * opts.failed   what to say if it does not         (authored)
 */
function openForm(opId, opts) {
	const shape = CIX_API[opId + "_SHAPE"];
	const options = opts || {};
	const form = document.getElementById("generated-form");
	const fields = shape && shape.request ? CIX_API.FIELDS[shape.request] || [] : [];
	const button = document.createElement("button");
	const allowed = sessionMay(opId);

	if (shape === undefined) {
		showStatus("No such operation: " + opId, true);
		return;
	}
	/*
	 * The modal opens BEFORE the fields are built, and the order is
	 * load-bearing: openModal() begins by calling closeModal(), which
	 * empties this form precisely so nothing typed survives a close.
	 * Building first and opening second would therefore have shown an
	 * empty form every time.
	 */
	openModal("generated-form", options.title || fieldLabel(opId));
	form.dataset.opId = opId;
	form.dataset.args = JSON.stringify(options.args || []);
	generatedFormAfter = options.after || refreshVisibleView;
	generatedFormFailed = options.failed || ("Failed to " + (options.submit || "submit"));

	for (const f of fields) {
		const label = document.createElement("label");

		/* A field the daemon only ever reports is not a field anyone
		 * fills in. */
		if (f.readOnly)
			continue;
		label.textContent = fieldLabel(f.name);
		label.appendChild(fieldControl(f));
		form.appendChild(label);
		if (f.description !== undefined) {
			const hint = document.createElement("p");

			hint.className = "hint";
			hint.textContent = f.description;
			form.appendChild(hint);
		}
	}
	button.type = "submit";
	button.textContent = options.submit || "Save";
	if (shape.destructive)
		button.className = "button-danger";
	/* web-ux-guidelines: a modal's own submit sets disabled and its
	 * reason from sessionMay() directly, since it must be re-enabled
	 * when a later login grants it. */
	button.disabled = !allowed;
	if (!allowed)
		button.title = sessionRefusal(opId);
	form.appendChild(button);
}
