/*
 * form.js -- the contract's own description of a request, as controls.
 *
 * GENERATED by nothing; this is the renderer that reads what apigen
 * generates (ADR-0338, #595). It is its own file for one reason: it has
 * no dependency on the dashboard at all beyond `document` and
 * `CIX_API`, which means a test can EXECUTE it rather than only parse
 * it -- `test_web_form` evals this file against a minimal DOM and
 * asserts that a `format: password` field really does produce an
 * obscured input, that an enum really does produce its own options, and
 * that an empty optional field really is omitted from the body.
 *
 * Keeping it inside app.js would have made that impossible: evaluating
 * that file runs a dashboard's worth of module-level wiring against
 * hundreds of element ids, so the only check it can ever have is that
 * it parses -- which is exactly the gap that let three unparseable
 * api.js releases through (#594).
 *
 * app.js owns the SUBMIT listener, and only that, because it is an HTTP
 * request and a status line and neither can be stubbed meaningfully.
 *
 * What this file expects app.js to have defined, which is the whole of
 * its dependency on the dashboard and is deliberately short enough to
 * stub in a test: `openModal`, `sessionMay`, `sessionRefusal`,
 * `showStatus`, `runRefreshers` and `refreshersForView`.
 */
/*
 * ---------- what a request schema becomes ----------
 *
 * One modal panel, built from the operation's own request schema, for
 * every create and edit the dashboard offers.
 *
 * The 36 hand-written forms this replaces re-typed what the contract
 * already states -- field names, types, which are required, which
 * values an enum allows -- and dropped what it states that is hardest
 * to re-type: 174 constraints, which reached the operator as a
 * round-trip 400 instead of as a form that would not submit. So the
 * split is ADR-0338's sixth principle exactly. GENERATED, because two
 * competent people would write it identically from the schema: the
 * fields, their order, their controls, their bounds, their hints.
 * AUTHORED at the call site, because it takes judgement: the modal's
 * title, the three words on its button, which resource list to refresh
 * afterwards, and what to say when it fails.
 *
 * A field's rendering is decided by the field, never by its name -- a
 * `name === "password"` special case here would be the parallel the
 * guidelines forbid, and is why the eight secrets an operator TYPES
 * carry `format: password` in the contract instead.
 */

/* The label a field name reads as. Derived, because the schema already
 * named the field; a hand-written label is the duplication principle 6
 * exists to stop. `prefix_len` reads as "Prefix len", which is plain
 * rather than pretty -- when that is genuinely wrong the fix is the
 * contract's own `x-cix-ui`, never a table here. */
function fieldLabel(name) {
	const words = name.replace(/_/g, " ");

	return words.charAt(0).toUpperCase() + words.slice(1);
}

/*
 * The one control a field's constraints describe.
 *
 * Every branch is a property of the schema and nothing else: options
 * make a select, boolean a checkbox, a numeric type a number input
 * carrying its own minimum and maximum, `format: password` an obscured
 * input, and a string its pattern and maxLength. An array of scalars is
 * a comma-separated text input, the convention the hand-written
 * container form already used for `dns_servers`.
 */
function fieldControl(f) {
	let el;

	if (Array.isArray(f.options) && f.options.length > 0) {
		el = document.createElement("select");
		if (!f.required) {
			const blank = document.createElement("option");

			blank.value = "";
			blank.textContent = "—";
			el.appendChild(blank);
		}
		for (const opt of f.options) {
			const o = document.createElement("option");

			o.value = opt;
			o.textContent = opt;
			el.appendChild(o);
		}
	} else if (f.type === "boolean") {
		el = document.createElement("input");
		el.type = "checkbox";
		if (f.fallback === true)
			el.checked = true;
	} else if (f.type === "integer" || f.type === "number") {
		el = document.createElement("input");
		el.type = "number";
		if (f.minimum !== undefined)
			el.min = String(f.minimum);
		if (f.maximum !== undefined)
			el.max = String(f.maximum);
		if (f.type === "integer")
			el.step = "1";
	} else {
		el = document.createElement("input");
		el.type = f.format === "password" ? "password" : "text";
		if (f.pattern !== undefined)
			el.pattern = f.pattern;
		if (f.maxLength !== undefined)
			el.maxLength = f.maxLength;
	}
	el.id = "gf-" + f.name;
	el.dataset.field = f.name;
	el.dataset.ftype = f.type;
	if (f.required && f.type !== "boolean")
		el.required = true;
	return el;
}

/*
 * What the operator typed, as the request body the schema describes.
 *
 * An empty optional field is OMITTED rather than sent as "", because
 * every partial-update endpoint in this API reads an absent key as
 * "leave it alone" and an empty string as "set it to empty" -- sending
 * the second for the first is how a generated form would quietly clear
 * a field nobody touched.
 */
function generatedFormBody(form) {
	const body = {};

	for (const el of form.querySelectorAll("[data-field]")) {
		const name = el.dataset.field;
		const type = el.dataset.ftype;

		if (type === "boolean") {
			body[name] = el.checked;
			continue;
		}
		if (el.value === "" && !el.required)
			continue;
		if (type === "integer" || type === "number") {
			body[name] = Number(el.value);
			continue;
		}
		if (type === "array") {
			body[name] = el.value
				.split(",")
				.map((s) => s.trim())
				.filter((s) => s.length > 0);
			continue;
		}
		body[name] = el.value;
	}
	return body;
}

/* The two things a submit needs that are not in the form: what to
 * refresh afterwards and what to say if it fails. Authored per call
 * site, held here because the one submit listener reads them. */
let generatedFormAfter = null;
let generatedFormFailed = "";

/*
 * The default `after`: whatever keeps the view the operator is looking
 * at honest.
 *
 * Every screen already declares its own refreshers in VIEW_REFRESHERS,
 * and both the poll loop and the tab bar run them that way -- so a
 * generated form needs no per-form refresh wiring at all. Each of the
 * 36 hand-written forms carried its own copy of that call, which is one
 * more thing that could be forgotten on the 37th.
 */
async function refreshVisibleView() {
	const view = document.querySelector(".view:not([hidden])");

	if (view !== null)
		await runRefreshers(refreshersForView(view.id));
}

/*
 * Open the generated form for one operation.
 *
 * opts.title    the modal's heading                (authored)
 * opts.submit   the words on the button            (authored)
 * opts.args     the operation's path parameters, in contract order
 * opts.after    what to refresh once it succeeds   (authored)
 * opts.failed   what to say if it does not         (authored)
 */
function openForm(opId, opts) {
	const shape = CIX_API[opId + "_SHAPE"];
	const options = opts || {};
	const form = document.getElementById("generated-form");
	const fields = shape && shape.request ? CIX_API.FIELDS[shape.request] || [] : [];
	const button = document.createElement("button");
	const allowed = sessionMay(opId);

	if (shape === undefined) {
		showStatus("No such operation: " + opId, true);
		return;
	}
	/*
	 * The modal opens BEFORE the fields are built, and the order is
	 * load-bearing: openModal() begins by calling closeModal(), which
	 * empties this form precisely so nothing typed survives a close.
	 * Building first and opening second would therefore have shown an
	 * empty form every time.
	 */
	openModal("generated-form", options.title || fieldLabel(opId));
	form.dataset.opId = opId;
	form.dataset.args = JSON.stringify(options.args || []);
	generatedFormAfter = options.after || refreshVisibleView;
	generatedFormFailed = options.failed || ("Failed to " + (options.submit || "submit"));

	for (const f of fields) {
		const label = document.createElement("label");

		/* A field the daemon only ever reports is not a field anyone
		 * fills in. */
		if (f.readOnly)
			continue;
		label.textContent = fieldLabel(f.name);
		/*
		 * A boolean uses the dashboard's own checkbox layout -- name
		 * beside a real-sized box, not above a full-width one. Without
		 * the class, the global `form input` rule (width: 100%,
		 * height: 2.25rem, which exists so text fields line up) makes
		 * a checkbox a large grey square. Rendering pkgInstall is what
		 * showed it; `form label.checkbox input[type="checkbox"]`
		 * already existed for the hand-written forms.
		 */
		if (f.type === "boolean")
			label.className = "checkbox";
		label.appendChild(fieldControl(f));
		/*
		 * The hint goes INSIDE the label, not beside it.
		 *
		 * A dashboard form is a grid -- `repeat(auto-fit, minmax(15rem,
		 * 1fr))` -- so a hint appended to the form is its own grid
		 * item and lands in the NEXT COLUMN, reading as a peer of the
		 * field rather than as its explanation. Rendering the real
		 * modal is what showed it: the syslog field sat in column one
		 * with its own description beside it in column two.
		 *
		 * The hand-written forms had the same shape, so this is not a
		 * regression -- but they carried 185 hints between them while
		 * the contract has a description for 583 fields, so what was
		 * an oddity on a few forms would have become the norm on every
		 * one. Inside the label, `form label`'s own flex column stacks
		 * name, control and hint as one cell.
		 */
		if (f.description !== undefined) {
			const hint = document.createElement("p");

			/*
			 * CLAMPED, with the whole thing on hover.
			 *
			 * The contract's descriptions are reference documentation
			 * -- 331 characters on average and up to 2,064 -- because
			 * that is the right length for the document they were
			 * written in. Rendered verbatim, a four-field form becomes
			 * a wall of prose taller than the modal: pkgInstall's four
			 * fields produced four paragraphs and pushed its own
			 * submit button off the bottom.
			 *
			 * Clamping is a DISPLAY decision and keeps the contract
			 * the source -- nothing is truncated in api.js, nothing is
			 * summarised, and `title` carries the full text. That is
			 * the difference between this and a first-sentence
			 * heuristic in the generator, which would have thrown the
			 * rest away for every reader.
			 */
			hint.className = "hint hint-clamp";
			hint.textContent = f.description;
			hint.title = f.description;
			label.appendChild(hint);
		}
		form.appendChild(label);
	}
	button.type = "submit";
	button.textContent = options.submit || "Save";
	if (shape.destructive)
		button.className = "button-danger";
	/* web-ux-guidelines: a modal's own submit sets disabled and its
	 * reason from sessionMay() directly, since it must be re-enabled
	 * when a later login grants it. */
	button.disabled = !allowed;
	if (!allowed)
		button.title = sessionRefusal(opId);
	form.appendChild(button);
}

/*
 * ---------- the primitives, and the two renderers over them ----------
 *
 * `fieldBlock` and `simpleTableRows` moved here from app.js unchanged
 * (83 and 15 callers, all unaffected -- both are globals). They are the
 * design system's PRIMITIVES layer: pure DOM builders with no screen
 * knowledge, which is both why they belong beside the renderers that
 * compose them and why they can be tested at all.
 */
function fieldBlock(label, value) {
	const row = document.createElement("tr");
	const labelCell = document.createElement("th");
	const valueCell = document.createElement("td");

	labelCell.className = "field-label";
	labelCell.scope = "row";
	labelCell.textContent = label;
	row.appendChild(labelCell);
	valueCell.textContent = value;
	row.appendChild(valueCell);
	return row;
}

function simpleTableRows(bodyEl, columns, colCount, emptyText) {
	bodyEl.textContent = "";
	if (columns.length === 0) {
		const row = document.createElement("tr");
		const cell = document.createElement("td");

		cell.colSpan = colCount;
		cell.className = "empty";
		cell.textContent = emptyText;
		row.appendChild(cell);
		bodyEl.appendChild(row);
		return;
	}
	for (const cols of columns) {
		const row = document.createElement("tr");

		for (const col of cols) {
			const cell = document.createElement("td");

			cell.textContent = col;
			row.appendChild(cell);
		}
		bodyEl.appendChild(row);
	}
}

/*
 * ONE VALUE, AS TEXT, DECIDED BY ITS FIELD.
 *
 * This is the half of the incoherence that is measurable rather than
 * aesthetic. Counted in app.js on 2026-10-10, before this existed:
 *
 *   a boolean reads "yes"/"no" 16 times, "enabled"/"disabled" 4 times
 *   and "true"/"false" once;
 *
 *   an absent value reads "-" 67 times, "none" 41, "unknown" 12,
 *   "unset" 4 and "—" 3.
 *
 * So the same fact reads five different ways depending on which page an
 * operator is looking at, and nothing anywhere decided that. The field
 * decides it now.
 *
 * The one subtlety is worth stating because the hand-written code had
 * it right and a naive version would get it wrong: an ABSENT boolean is
 * not unknown if its schema declares a default. `s.enabled === false ?
 * "no" : "yes"` is in app.js today for a field that defaults to true,
 * and it is correct -- so the contract's own `default` (emitted as
 * `fallback`) is consulted before anything is called absent.
 */
const FIELD_ABSENT = "—";

function fieldText(f, value) {
	const type = f !== undefined ? f.type : "string";
	let v = value;

	if ((v === undefined || v === null) && f !== undefined && f.fallback !== undefined)
		v = f.fallback;
	if (v === undefined || v === null)
		return FIELD_ABSENT;
	if (type === "boolean")
		return v ? "yes" : "no";
	if (type === "array") {
		if (!Array.isArray(v) || v.length === 0)
			return FIELD_ABSENT;
		return v.join(", ");
	}
	if (type === "object")
		return FIELD_ABSENT;
	if (v === "")
		return FIELD_ABSENT;
	return String(v);
}

/* The field descriptor for one name, or undefined. */
function schemaField(schema, name) {
	const fields = CIX_API.FIELDS[schema];

	if (fields === undefined)
		return undefined;
	return fields.find((f) => f.name === name);
}

/*
 * A list table's rows, from the schema and an AUTHORED column list.
 *
 * Which columns a table shows and in what order is judgement -- the
 * `networks` table shows 4 of `Network`'s 7 fields, because
 * `has_address` is a flag the Address cell renders from and `management`
 * and `interfaces` are not what that page is for. So `columns` is the
 * authored part, as field names or `{ field, label }` pairs, and
 * everything else is derived: the cell's text comes from the field's own
 * type, through fieldText(), so a boolean reads the same here as it does
 * on a detail page.
 *
 * The header stays in index.html for now. Generating it is a separate
 * change across 62 tables, and doing it in the same breath as this
 * would make one diff that has to be right about two things.
 */
function renderTableRows(bodyEl, schema, rows, columns, emptyText) {
	const cells = rows.map((row) =>
		columns.map((col) => {
			const name = typeof col === "string" ? col : col.field;

			return fieldText(schemaField(schema, name), row[name]);
		}));

	simpleTableRows(bodyEl, cells, columns.length, emptyText);
}

/*
 * A detail page's key/value rows, in SCHEMA order.
 *
 * Schema order rather than an authored list, because a detail page's job
 * is to show everything known about one resource -- when a page wants a
 * subset it passes one, and when it does not, adding a field to the
 * contract makes it appear rather than being silently absent until
 * someone notices.
 *
 * A read-only field is shown (unlike a form, which omits it): "the
 * daemon reports this and you cannot set it" is exactly what a detail
 * page is for.
 */
function renderDetailRows(bodyEl, schema, obj, only) {
	const fields = CIX_API.FIELDS[schema] || [];

	bodyEl.textContent = "";
	for (const f of fields) {
		if (Array.isArray(only) && !only.includes(f.name))
			continue;
		bodyEl.appendChild(fieldBlock(fieldLabel(f.name), fieldText(f, obj[f.name])));
	}
}
