/*
 * form.js -- the contract's own description of a request, as controls.
 *
 * GENERATED by nothing; this is the renderer that reads what apigen
 * generates (ADR-0338, #595). It is its own file for one reason: it has
 * no dependency on the dashboard at all beyond `document` and
 * `CIX_API`, which means a test can EXECUTE it rather than only parse
 * it -- `test_web_form` evals this file against a minimal DOM and
 * asserts that a `format: password` field really does produce an
 * obscured input, that an enum really does produce its own options, and
 * that an empty optional field really is omitted from the body.
 *
 * Keeping it inside app.js would have made that impossible: evaluating
 * that file runs a dashboard's worth of module-level wiring against
 * hundreds of element ids, so the only check it can ever have is that
 * it parses -- which is exactly the gap that let three unparseable
 * api.js releases through (#594).
 *
 * app.js owns the SUBMIT listener, and only that, because it is an HTTP
 * request and a status line and neither can be stubbed meaningfully.
 *
 * What this file expects app.js to have defined, which is the whole of
 * its dependency on the dashboard and is deliberately short enough to
 * stub in a test: `openModal`, `sessionMay`, `sessionRefusal`,
 * `showStatus`, `runRefreshers`, `refreshersForView` and
 * `qualifyHostname`. The last one is site knowledge -- what this
 * host's own domain is -- which only app.js has.
 */
/*
 * ---------- what a request schema becomes ----------
 *
 * One modal panel, built from the operation's own request schema, for
 * every create and edit the dashboard offers.
 *
 * The 36 hand-written forms this replaces re-typed what the contract
 * already states -- field names, types, which are required, which
 * values an enum allows -- and dropped what it states that is hardest
 * to re-type: 174 constraints, which reached the operator as a
 * round-trip 400 instead of as a form that would not submit. So the
 * split is ADR-0338's sixth principle exactly. GENERATED, because two
 * competent people would write it identically from the schema: the
 * fields, their order, their controls, their bounds, their hints.
 * AUTHORED at the call site, because it takes judgement: the modal's
 * title, the three words on its button, which resource list to refresh
 * afterwards, and what to say when it fails.
 *
 * A field's rendering is decided by the field, never by its name -- a
 * `name === "password"` special case here would be the parallel the
 * guidelines forbid, and is why the eight secrets an operator TYPES
 * carry `format: password` in the contract instead.
 */

/*
 * THE OPERATOR'S WORD FOR A FIELD, which is the contract's `title`.
 *
 * The fallback de-cases the schema key, and that is all it can do:
 * `sn` becomes "Sn", `ip` becomes "Ip", `uidnumber` becomes
 * "Uidnumber". Those are real renders from a real form and they are
 * the dashboard speaking its own schema's vocabulary at a person --
 * what web-ux-guidelines' fifth principle exists to forbid. So the
 * fallback is a LAST RESORT and not the design: the Primitives board
 * puts the rule in one line, *"a label that needs to differ goes in
 * the contract, not in app.js"*, and JSON Schema's own `title` is
 * where it goes.
 *
 * It still takes a bare name as well as a field, because the modal's
 * own heading falls back to the operation id when no title is
 * authored at the call site.
 */
function fieldLabel(f) {
	const name = typeof f === "string" ? f : f.name;
	const words = name.replace(/_/g, " ");

	if (typeof f === "object" && f.title)
		return f.title;
	return words.charAt(0).toUpperCase() + words.slice(1);
}

/*
 * THE CONSTRAINT, IN THE OPERATOR'S SIGHT RATHER THAN ONLY IN THE
 * INPUT -- the monospace chip the Generated board puts to the right of
 * every label (`1-15 · [A-Za-z0-9-]`, `8 - 30`).
 *
 * Derived entirely, because every part of it is already a fact of the
 * schema. The point is not decoration: a `pattern` that silently
 * refuses a keystroke is worse than one the operator can read, and
 * until this existed the contract's 174 constraints were invisible
 * until the form would not submit.
 *
 * A pattern is shown as its CHARACTER CLASS rather than as the regex,
 * because `^[A-Za-z0-9_\-]+$` is not a thing to put in front of
 * someone. Where that cannot be extracted the pattern is not shown at
 * all -- an unreadable chip is worse than no chip, and the hint still
 * carries the rule in words.
 */
function constraintText(f) {
	const parts = [];
	const lo = f.minimum !== undefined;
	const hi = f.maximum !== undefined;
	let cls = null;

	if (lo && hi)
		parts.push(f.minimum + " – " + f.maximum);
	else if (lo)
		parts.push("≥ " + f.minimum);
	else if (hi)
		parts.push("≤ " + f.maximum);

	if (f.pattern !== undefined) {
		/*
		 * The END-anchored class first, then the first class as a
		 * fallback. Two real shapes in this contract need both:
		 * `^[a-z_][a-z0-9_\-]*$` leads with a one-character anchor
		 * class and the meaningful one is at the end, while a
		 * hostname's `^[A-Za-z0-9\-]{1,63}(\.…)*$` ends inside a
		 * group and the meaningful one is first. `\-` reads as `-`,
		 * since that spelling is for the regex engine and not for a
		 * person.
		 */
		const m = /\[([^\]]+)\](\{(\d+),(\d+)\})?[+*]?\$?$/.exec(f.pattern) ||
			/\[([^\]]+)\](\{(\d+),(\d+)\})?/.exec(f.pattern);

		if (m !== null) {
			cls = "[" + m[1].replace(/\\-/g, "-") + "]";
			if (m[3] !== undefined)
				parts.push(m[3] + "–" + m[4]);
		}
	}
	if (f.maxLength !== undefined && f.pattern === undefined)
		parts.push("≤ " + f.maxLength + " chars");
	if (cls !== null)
		parts.push(cls);
	/*
	 * A standard `format`, in words, when nothing numeric was derived
	 * -- the board's chip for `subnet` is "dotted quad", which is what
	 * `format: ipv4` means to a person. The map is RENDERING, the same
	 * kind of decision as `format: password` producing an obscured
	 * input; the fact itself stays in the contract.
	 */
	if (parts.length === 0 && f.format !== undefined && FORMAT_WORD[f.format] !== undefined)
		parts.push(FORMAT_WORD[f.format]);
	return parts.join(" · ");
}

const FORMAT_WORD = {
	ipv4: "dotted quad",
	ipv6: "IPv6",
	hostname: "hostname",
	"date-time": "RFC 3339",
	uri: "URL",
	email: "email",
	byte: "base64",
};

/*
 * ONE SENTENCE, not the reference paragraph.
 *
 * The contract's `description` is API documentation -- 214 characters
 * on average, up to 2,064 -- and rendering it under every input turns
 * a four-field form into a wall of prose. Clamping it to three lines
 * was the first attempt and it was wrong: it hid the symptom and left
 * a sentence cut mid-word.
 *
 * Measured across this contract on 2026-10-10: of 684 property
 * descriptions, 89% have a first sentence that works as a hint on its
 * own, mean 81 characters. So the first sentence IS the hint, the
 * whole description stays on the label's `title` for hover, and the
 * convention that follows is a writing rule rather than a second key:
 * **the first sentence of a property description is what an operator
 * needs; everything after it is reference detail.** The 11% that do
 * not comply are a contract fix, and `test_apigen` names them.
 *
 * An abbreviation is why this is not a bare split on ". " -- "e.g. "
 * and "i.e. " end no sentence, and the contract uses both. A scan
 * rather than a regex with a sentinel: the sentinel version of this
 * function wrote two literal NUL bytes into this file, which git saw
 * as a binary change.
 */
const HINT_ABBREV = ["e.g.", "i.e.", "cf.", "vs.", "approx.", "etc."];

function fieldHint(f) {
	if (f.description === undefined)
		return "";
	const text = f.description.replace(/\s+/g, " ").trim();
	let at = 0;

	for (;;) {
		const dot = text.indexOf(". ", at);

		if (dot < 0)
			return text;
		const upto = text.slice(0, dot + 1);
		let abbrev = false;

		for (const a of HINT_ABBREV)
			if (upto.endsWith(a))
				abbrev = true;
		if (!abbrev)
			return upto;
		at = dot + 2;
	}
}

/*
 * The one control a field's constraints describe.
 *
 * Every branch is a property of the schema and nothing else: options
 * make a select, boolean a checkbox, a numeric type a number input
 * carrying its own minimum and maximum, `format: password` an obscured
 * input, and a string its pattern and maxLength. An array of scalars is
 * a comma-separated text input, the convention the hand-written
 * container form already used for `dns_servers`.
 */
function fieldControl(f) {
	let el;

	/*
	 * `ui` FIRST, because it is the contract overriding a derivation
	 * it has already judged wrong (ADR-0338) -- a derived control that
	 * won over an explicit one would make the override unreliable in
	 * exactly the cases it exists for.
	 *
	 * Only `textarea` is known, and nothing else can reach here:
	 * apigen refuses any other value of `x-cix-ui` at generation,
	 * because a control this function does not know would fall through
	 * to a plain text input and be silently wrong. The refusal belongs
	 * there rather than in a throw here, which would take a form down
	 * in a browser over a contract typo.
	 *
	 * An `object` field needs no annotation and gets one anyway: a
	 * free-form object (`additionalProperties`, so the contract names
	 * no properties to render) is typed as JSON, and a one-line text
	 * input is never the right control for JSON. That is DERIVED,
	 * which is the rule -- `x-cix-ui` exists for the string case,
	 * where the schema really does say nothing.
	 *
	 * The row counts are the one judgement here: a document field
	 * holds a recipe (the hand-written forms it replaces used 10 and
	 * 16), a JSON object field holds a handful of keys (they used 3
	 * and 6). `resize: vertical` means neither is a ceiling.
	 */
	if (f.ui === "textarea" || f.type === "object") {
		el = document.createElement("textarea");
		el.rows = f.type === "object" ? 6 : 12;
		el.spellcheck = false;
		if (f.maxLength !== undefined)
			el.maxLength = f.maxLength;
	} else if (Array.isArray(f.options) && f.options.length > 0) {
		el = document.createElement("select");
		if (!f.required) {
			const blank = document.createElement("option");

			blank.value = "";
			blank.textContent = "—";
			el.appendChild(blank);
		}
		for (const opt of f.options) {
			const o = document.createElement("option");

			o.value = opt;
			o.textContent = opt;
			el.appendChild(o);
		}
	} else if (f.type === "boolean") {
		el = document.createElement("input");
		el.type = "checkbox";
		if (f.fallback === true)
			el.checked = true;
	} else if (f.type === "integer" || f.type === "number") {
		el = document.createElement("input");
		el.type = "number";
		if (f.minimum !== undefined)
			el.min = String(f.minimum);
		if (f.maximum !== undefined)
			el.max = String(f.maximum);
		if (f.type === "integer")
			el.step = "1";
	} else {
		el = document.createElement("input");
		el.type = f.format === "password" ? "password" : "text";
		if (f.pattern !== undefined)
			el.pattern = f.pattern;
		if (f.maxLength !== undefined)
			el.maxLength = f.maxLength;
		/*
		 * `format: hostname` -- OpenAPI's own standard format, read
		 * the same way `format: password` is, and it earns the
		 * dashboard's bare-label convenience: typing `db` leaves the
		 * field as `db.<site>.<domain>`.
		 *
		 * That used to be wired by hand onto two specific element ids
		 * (`df-name`, `pf-name`), which is why only those two had it
		 * -- a convenience attached to an id rather than to a KIND OF
		 * FIELD cannot reach the next hostname field anyone adds. The
		 * site's own suffix is app.js's to know, so the behaviour is
		 * a global this file declares (see the header) rather than
		 * something derived here.
		 */
		if (f.format === "hostname")
			qualifyHostname(el);
	}
	el.id = "gf-" + f.name;
	el.dataset.field = f.name;
	el.dataset.ftype = f.type;
	/*
	 * An array's ITEM type, because a comma-separated list of digits
	 * is not a list of numbers until someone converts it (#596).
	 *
	 * `LdapUserCreateRequest.secondary_groups` is `items: integer`,
	 * and without this the body carried `["10001","10002"]` -- which
	 * the daemon reads with json_as_number() on a JSON string, so
	 * every gid would have arrived as 0 and the user would have been
	 * put in no secondary group at all. Found by rendering the real
	 * form and printing the body it collects, not by reading.
	 */
	if (f.type === "array" && f.items !== undefined)
		el.dataset.fitems = f.items;
	if (f.required && f.type !== "boolean")
		el.required = true;
	return el;
}

/*
 * What the operator typed, as the request body the schema describes.
 *
 * An empty optional field is OMITTED rather than sent as "", because
 * every partial-update endpoint in this API reads an absent key as
 * "leave it alone" and an empty string as "set it to empty" -- sending
 * the second for the first is how a generated form would quietly clear
 * a field nobody touched.
 */
function generatedFormBody(form) {
	const body = {};

	for (const el of form.querySelectorAll("[data-field]")) {
		const name = el.dataset.field;
		const type = el.dataset.ftype;

		if (type === "boolean") {
			body[name] = el.checked;
			continue;
		}
		/*
		 * A free-form object -- `additionalProperties`, so the
		 * contract names no fields to render -- is typed as JSON and
		 * parsed here. `secrets` on applyDeployment is the first.
		 *
		 * It THROWS rather than reporting, because the one submit
		 * listener already calls this inside its own try/catch and
		 * shows the message on the status line without closing the
		 * modal: the typed text survives, which is the whole point
		 * when the text is the thing that was mistyped.
		 *
		 * Trimmed before the emptiness test below, because a textarea
		 * the operator tabbed through holds a newline rather than "".
		 */
		if (type === "object") {
			const text = el.value.trim();
			let parsed;

			if (text === "") {
				if (!el.required)
					continue;
				throw new Error(fieldLabel(name) + " is required");
			}
			try {
				parsed = JSON.parse(text);
			} catch (e) {
				throw new Error(fieldLabel(name) + " must be valid JSON: " +
				                e.message);
			}
			if (parsed === null || typeof parsed !== "object" ||
			    Array.isArray(parsed))
				throw new Error(fieldLabel(name) +
				                " must be a JSON object, not a bare value");
			body[name] = parsed;
			continue;
		}
		if (el.value === "" && !el.required)
			continue;
		if (type === "integer" || type === "number") {
			body[name] = Number(el.value);
			continue;
		}
		if (type === "array") {
			const items = el.value
				.split(",")
				.map((s) => s.trim())
				.filter((s) => s.length > 0);
			const itemType = el.dataset.fitems;

			/* The item type decides, exactly as the field's own type
			 * decides a scalar -- a numeric list sent as strings is
			 * read by the daemon's json_as_number() as a list of
			 * zeroes, which is silent and wrong rather than refused. */
			body[name] = itemType === "integer" || itemType === "number"
				? items.map((s) => Number(s))
				: items;
			continue;
		}
		body[name] = el.value;
	}
	return body;
}

/* The two things a submit needs that are not in the form: what to
 * refresh afterwards and what to say if it fails. Authored per call
 * site, held here because the one submit listener reads them. */
let generatedFormAfter = null;
let generatedFormFailed = "";

/*
 * The default `after`: whatever keeps the view the operator is looking
 * at honest.
 *
 * Every screen already declares its own refreshers in VIEW_REFRESHERS,
 * and both the poll loop and the tab bar run them that way -- so a
 * generated form needs no per-form refresh wiring at all. Each of the
 * 36 hand-written forms carried its own copy of that call, which is one
 * more thing that could be forgotten on the 37th.
 */
async function refreshVisibleView() {
	const view = document.querySelector(".view:not([hidden])");

	if (view !== null)
		await runRefreshers(refreshersForView(view.id));
}

/*
 * One value into its control, whatever control the field got.
 *
 * The inverse of generatedFormBody()'s own per-type reading, and it has
 * to be, or a form opened on a resource and submitted unchanged would
 * send something different from what it was given -- an array shown as
 * "a,b" and read back by splitting on commas, an object shown as JSON
 * and read back by parsing it.
 */
function setFieldValue(el, f, v) {
	if (v === undefined || v === null)
		return;
	if (f.type === "boolean") {
		el.checked = v === true;
		return;
	}
	if (f.type === "array") {
		el.value = Array.isArray(v) ? v.join(", ") : String(v);
		return;
	}
	if (f.type === "object") {
		/* Indented, because the operator is about to read and edit it
		 * -- JSON.stringify's default one-line form is not a thing
		 * anyone edits in a textarea. */
		el.value = typeof v === "string" ? v : JSON.stringify(v, null, 2);
		return;
	}
	el.value = String(v);
}

/*
 * Open the generated form for one operation.
 *
 * opts.title    the modal's heading                (authored)
 * opts.submit   the words on the button            (authored)
 * opts.args     the operation's path parameters, in contract order
 * opts.after    what to refresh once it succeeds   (authored)
 * opts.failed   what to say if it does not         (authored)
 * opts.values   starting values, by field name -- a draft to edit
 * opts.fixed    values that IDENTIFY the resource, so not editable
 *
 * `values` and `fixed` are two different facts and not one with a flag.
 * An upsert keyed by a body field -- addImageRecipe, addDeployment --
 * is the SAME operation for a create and for an edit, and the only
 * difference is that on an edit the key names a resource that already
 * exists: typing over it would not rename anything, it would quietly
 * address a different one. So `fixed` renders read-only and is still
 * SENT, because the operation needs it. That is a separate thing from
 * the contract's own `readOnly`, which means the daemon reports this
 * field and never accepts it -- those fields are not rendered at all.
 */
function openForm(opId, opts) {
	const shape = CIX_API[opId + "_SHAPE"];
	const options = opts || {};
	const form = document.getElementById("generated-form");
	const fields = shape && shape.request ? CIX_API.FIELDS[shape.request] || [] : [];
	const button = document.createElement("button");
	const allowed = sessionMay(opId);

	if (shape === undefined) {
		showStatus("No such operation: " + opId, true);
		return;
	}
	/*
	 * The modal opens BEFORE the fields are built, and the order is
	 * load-bearing: openModal() begins by calling closeModal(), which
	 * empties this form precisely so nothing typed survives a close.
	 * Building first and opening second would therefore have shown an
	 * empty form every time.
	 */
	openModal("generated-form", options.title || fieldLabel(opId));
	form.dataset.opId = opId;
	form.dataset.args = JSON.stringify(options.args || []);
	generatedFormAfter = options.after || refreshVisibleView;
	generatedFormFailed = options.failed || ("Failed to " + (options.submit || "submit"));

	for (const f of fields) {
		const label = document.createElement("label");
		const values = options.values || {};
		const fixed = options.fixed || {};
		let control;
		let head;
		let name;
		let rule;
		let req;

		/* A field the daemon only ever reports is not a field anyone
		 * fills in. */
		if (f.readOnly)
			continue;
		/*
		 * The label ROW, which the Generated board specifies as three
		 * things on one line: the operator's word, whether the field
		 * is required, and the constraint in monospace on the right.
		 *
		 * All three are facts the schema already states and that the
		 * dashboard used to keep to itself -- a required field looked
		 * exactly like an optional one, and the 174 constraints were
		 * enforced invisibly by the input until it refused to submit.
		 */
		head = document.createElement("span");
		head.className = "field-head";
		name = document.createElement("span");
		name.className = "field-name";
		name.textContent = fieldLabel(f);
		head.appendChild(name);
		/* Both words, as the board draws them. Marking only the
		 * exception was the tidier instinct and it is wrong here: an
		 * unmarked field reads as "nobody said", and a form an
		 * operator is meeting for the first time should not make them
		 * infer which of the two it is. */
		req = document.createElement("span");
		req.className = f.required ? "field-req" : "field-opt";
		req.textContent = f.required ? "required" : "optional";
		head.appendChild(req);
		rule = constraintText(f);
		if (rule !== "") {
			const chip = document.createElement("span");

			chip.className = "field-rule";
			chip.textContent = rule;
			head.appendChild(chip);
		}
		label.appendChild(head);
		/*
		 * A boolean uses the dashboard's own checkbox layout -- name
		 * beside a real-sized box, not above a full-width one. Without
		 * the class, the global `form input` rule (width: 100%,
		 * height: 2.25rem, which exists so text fields line up) makes
		 * a checkbox a large grey square. Rendering pkgInstall is what
		 * showed it; `form label.checkbox input[type="checkbox"]`
		 * already existed for the hand-written forms.
		 */
		if (f.type === "boolean")
			label.className = "checkbox";
		/*
		 * No `.wide` here any more: the generated form is one column,
		 * so every field already spans it. The class stays in the
		 * stylesheet for the hand-written forms, which are still
		 * grids.
		 */
		control = fieldControl(f);
		/* `readOnly` is right for every `fixed` field there is or is
		 * likely to be -- a key is a name, so a text input. It is
		 * inert on a `<select>`, so a fixed enum would show as
		 * editable; that is a real gap and not a current one, and the
		 * fix when it arrives is `disabled` plus keeping the value in
		 * the body, which generatedFormBody() already would. */
		if (Object.prototype.hasOwnProperty.call(fixed, f.name)) {
			setFieldValue(control, f, fixed[f.name]);
			control.readOnly = true;
		} else {
			setFieldValue(control, f, values[f.name]);
		}
		label.appendChild(control);
		/*
		 * The hint goes INSIDE the label, not beside it.
		 *
		 * A dashboard form is a grid -- `repeat(auto-fit, minmax(15rem,
		 * 1fr))` -- so a hint appended to the form is its own grid
		 * item and lands in the NEXT COLUMN, reading as a peer of the
		 * field rather than as its explanation. Rendering the real
		 * modal is what showed it: the syslog field sat in column one
		 * with its own description beside it in column two.
		 *
		 * The hand-written forms had the same shape, so this is not a
		 * regression -- but they carried 185 hints between them while
		 * the contract has a description for 583 fields, so what was
		 * an oddity on a few forms would have become the norm on every
		 * one. Inside the label, `form label`'s own flex column stacks
		 * name, control and hint as one cell.
		 */
		if (f.description !== undefined) {
			const hint = document.createElement("p");

			/*
			 * CLAMPED, with the whole thing on hover.
			 *
			 * The contract's descriptions are reference documentation
			 * -- 331 characters on average and up to 2,064 -- because
			 * that is the right length for the document they were
			 * written in. Rendered verbatim, a four-field form becomes
			 * a wall of prose taller than the modal: pkgInstall's four
			 * fields produced four paragraphs and pushed its own
			 * submit button off the bottom.
			 *
			 * Clamping is a DISPLAY decision and keeps the contract
			 * the source -- nothing is truncated in api.js, nothing is
			 * summarised, and `title` carries the full text. That is
			 * the difference between this and a first-sentence
			 * heuristic in the generator, which would have thrown the
			 * rest away for every reader.
			 */
			hint.className = "hint";
			hint.textContent = fieldHint(f);
			/* The whole thing on hover, so nothing is lost -- the
			 * contract stays the source and this is a display
			 * decision, the same split the clamp was reaching for and
			 * getting wrong. */
			hint.title = f.description;
			label.appendChild(hint);
		}
		form.appendChild(label);
	}
	button.type = "submit";
	button.textContent = options.submit || "Save";
	if (shape.destructive)
		button.className = "button-danger";
	/* web-ux-guidelines: a modal's own submit sets disabled and its
	 * reason from sessionMay() directly, since it must be re-enabled
	 * when a later login grants it. */
	button.disabled = !allowed;
	if (!allowed)
		button.title = sessionRefusal(opId);
	form.appendChild(button);
}

/*
 * ---------- the primitives, and the two renderers over them ----------
 *
 * `fieldBlock` and `simpleTableRows` moved here from app.js unchanged
 * (83 and 15 callers, all unaffected -- both are globals). They are the
 * design system's PRIMITIVES layer: pure DOM builders with no screen
 * knowledge, which is both why they belong beside the renderers that
 * compose them and why they can be tested at all.
 */
function fieldBlock(label, value) {
	const row = document.createElement("tr");
	const labelCell = document.createElement("th");
	const valueCell = document.createElement("td");

	labelCell.className = "field-label";
	labelCell.scope = "row";
	labelCell.textContent = label;
	row.appendChild(labelCell);
	valueCell.textContent = value;
	row.appendChild(valueCell);
	return row;
}

function simpleTableRows(bodyEl, columns, colCount, emptyText) {
	bodyEl.textContent = "";
	if (columns.length === 0) {
		const row = document.createElement("tr");
		const cell = document.createElement("td");

		cell.colSpan = colCount;
		cell.className = "empty";
		cell.textContent = emptyText;
		row.appendChild(cell);
		bodyEl.appendChild(row);
		return;
	}
	for (const cols of columns) {
		const row = document.createElement("tr");

		for (const col of cols) {
			const cell = document.createElement("td");

			cell.textContent = col;
			row.appendChild(cell);
		}
		bodyEl.appendChild(row);
	}
}

/*
 * ONE VALUE, AS TEXT, DECIDED BY ITS FIELD.
 *
 * This is the half of the incoherence that is measurable rather than
 * aesthetic. Counted in app.js on 2026-10-10, before this existed:
 *
 *   a boolean reads "yes"/"no" 16 times, "enabled"/"disabled" 4 times
 *   and "true"/"false" once;
 *
 *   an absent value reads "-" 67 times, "none" 41, "unknown" 12,
 *   "unset" 4 and "—" 3.
 *
 * So the same fact reads five different ways depending on which page an
 * operator is looking at, and nothing anywhere decided that. The field
 * decides it now.
 *
 * The one subtlety is worth stating because the hand-written code had
 * it right and a naive version would get it wrong: an ABSENT boolean is
 * not unknown if its schema declares a default. `s.enabled === false ?
 * "no" : "yes"` is in app.js today for a field that defaults to true,
 * and it is correct -- so the contract's own `default` (emitted as
 * `fallback`) is consulted before anything is called absent.
 */
const FIELD_ABSENT = "—";

function fieldText(f, value) {
	const type = f !== undefined ? f.type : "string";
	let v = value;

	if ((v === undefined || v === null) && f !== undefined && f.fallback !== undefined)
		v = f.fallback;
	if (v === undefined || v === null)
		return FIELD_ABSENT;
	if (type === "boolean")
		return v ? "yes" : "no";
	if (type === "array") {
		if (!Array.isArray(v) || v.length === 0)
			return FIELD_ABSENT;
		return v.join(", ");
	}
	if (type === "object")
		return FIELD_ABSENT;
	if (v === "")
		return FIELD_ABSENT;
	return String(v);
}

/* The field descriptor for one name, or undefined. */
function schemaField(schema, name) {
	const fields = CIX_API.FIELDS[schema];

	if (fields === undefined)
		return undefined;
	return fields.find((f) => f.name === name);
}

/*
 * A list table's rows, from the schema and an AUTHORED column list.
 *
 * Which columns a table shows and in what order is judgement -- the
 * `networks` table shows 4 of `Network`'s 7 fields, because
 * `has_address` is a flag the Address cell renders from and `management`
 * and `interfaces` are not what that page is for. So `columns` is the
 * authored part, as field names or `{ field, label }` pairs, and
 * everything else is derived: the cell's text comes from the field's own
 * type, through fieldText(), so a boolean reads the same here as it does
 * on a detail page.
 *
 * The header stays in index.html for now. Generating it is a separate
 * change across 62 tables, and doing it in the same breath as this
 * would make one diff that has to be right about two things.
 */
function renderTableRows(bodyEl, schema, rows, columns, emptyText) {
	const cells = rows.map((row) =>
		columns.map((col) => {
			const name = typeof col === "string" ? col : col.field;

			return fieldText(schemaField(schema, name), row[name]);
		}));

	simpleTableRows(bodyEl, cells, columns.length, emptyText);
}

/*
 * A detail page's key/value rows, in SCHEMA order.
 *
 * Schema order rather than an authored list, because a detail page's job
 * is to show everything known about one resource -- when a page wants a
 * subset it passes one, and when it does not, adding a field to the
 * contract makes it appear rather than being silently absent until
 * someone notices.
 *
 * A read-only field is shown (unlike a form, which omits it): "the
 * daemon reports this and you cannot set it" is exactly what a detail
 * page is for.
 */
function renderDetailRows(bodyEl, schema, obj, only) {
	const fields = CIX_API.FIELDS[schema] || [];

	bodyEl.textContent = "";
	for (const f of fields) {
		if (Array.isArray(only) && !only.includes(f.name))
			continue;
		bodyEl.appendChild(fieldBlock(fieldLabel(f.name), fieldText(f, obj[f.name])));
	}
}
